-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: DRAGON BALL GEKISHIN SQUADRA EM

addappid(2572370)

addappid(2572371,0,"bccfea1acaa83f7e151c2ae16369f8a1d94f8818362127f541b6366b052fc6dc")
