-- generated by KeySteam
-- update time: 2023-01-13
-- app_name: 欢迎来到阿鲁毕恩！

addappid(1885520)

addappid(1885521,0,"ed5260a92ee63cc49d683c59b68bc23caa66336af0064c76bb6abfc97b95ce7e")

addappid(2640430)