-- generated by KeySteam
-- update time: 2022-12-13
-- app_name: 所向之未来 - Towards Future

addappid(1888010)

addappid(1888011,0,"a8749bc9ee27d3c5bcb4ae87c6f02fff4b4c9624ed909184aa066b9299d33e7d")

addappid(1888090)