-- generated by KeySteam
-- update time: 2026-02-11
-- app_name: Pixel Puzzles Illustrations & Anime Jigsaw Puzzles

addappid(1005240,0,"4bfc832d8418071a2cc6b3db4d7180bfc0540b04d5b9f01e0471abed9a9192ae")

addappid(1005241,0,"ca76c73881bb2164be62cd5962f965896b9d6643c56ada9f01a8f8ffc1d6325d")
addappid(1561410,0,"e4b3b139d9bf9a67f94ff987aff8c982bc951152d94c2b57e2a04fa868b6a4d3")
