-- generated by KeySteam
-- update time: 2020-06-04
-- app_name: Fantasia of the Wind 2 风之幻想曲 第二部

addappid(1006400)

addappid(1006401,0,"e18fb5776d0cfeef46eef762368c16490373c431a50025b65e9fbb63425e691b")

addappid(1007341)