-- generated by KeySteam
-- update time: 2024-08-31
-- app_name: Touhou Fantasia

addappid(1010890)

addappid(1010891,0,"2e792d6949a5221a2fa1e7e739f63b7a689d746b90b73f2daf51071e127cdbc2")

addappid(1118430)