-- generated by KeySteam
-- update time: 2025-01-21
-- app_name: Chernobylite Complete Edition

addappid(1016800)

addappid(1016801,0,"d5922db497812c1e9e7de0a1242522c0a4f38964b632aafe2f466105a69429bb")

addappid(1640500)
addappid(1701200)
addappid(1797280)
addappid(1845330)
addappid(1903090)
addappid(1935250)
addappid(1958580)
addappid(2094140)
addappid(2184830)
addappid(3017050)