-- generated by KeySteam
-- update time: 2023-07-14
-- app_name: Smile For Me

addappid(1018850)

addappid(1018851,0,"334de51773c71fca5ccb8722c0ff765563479be38c632c41d0fa15093c1e7eb4")

addappid(1065220)