-- generated by KeySteam
-- update time: 2019-12-29
-- app_name: InductVR (beta)

addappid(907180)

addappid(907181,0,"669eadcc4fa122b60b2dc9584d9c2baf7fda7367cde3a0ea7c7978b238ffe507")

addappid(1083970)
addappid(1083971)