-- generated by KeySteam
-- update time: 2020-10-22
-- app_name: Dusk Diver 酉閃町

addappid(911220)

addappid(911223,0,"fbe7931e52b91746c65969190b0a2c3d12d3834ccbcedc3cd7cb5c818e28a810")

addappid(1036112)
addappid(1036114)
addappid(1036116)
addappid(1036117)