-- generated by KeySteam
-- update time: 2022-07-20
-- app_name: The Tale of Bistun

addappid(916140)

addappid(916141,0,"878ee4680efaf543fae9eb2f56b65434af9f52c3185a6eb54d91ddbf9d35f5af")

addappid(2081750)