-- generated by KeySteam
-- update time: 2024-01-21
-- app_name: 超战女武神

addappid(2464800)

addappid(2464801,0,"4c0f217e0b65b3096267000a7fa5bc9727d68dcb5836ed40fb7ec7ffd2930306")

addappid(2739750)
addappid(2742270)
addappid(2742310)
addappid(2742320)
addappid(2742340)
addappid(2742380)
addappid(2742400)
addappid(2742420)
addappid(2743570)
addappid(2743640)
addappid(2743680)