-- generated by KeySteam
-- update time: 2020-11-14
-- app_name: White Wings 白色之翼

addappid(1185680)

addappid(1185681,0,"a0dde99ee657f5a61a2e536c6fd061bfd111245478d0509d027b8a6af66825e1")

addappid(1187260)
addappid(1204160)