-- generated by KeySteam
-- update time: 2025-03-07
-- app_name: Arthur's Quest: Between the Big Sword and the Bara Spirits

addappid(3302110)

addappid(3302111,0,"39204801e28cd57de5c7b32175b201be5ecee614e7c33395b7ad2e968d48785c")

addappid(3302280)
addappid(3302290)
addappid(3302300)