-- generated by KeySteam
-- update time: 2026-03-06
-- app_name: Katana Dragon: Chapter 1

addappid(3303010)

addappid(3303011,0,"6162f374449a9ca0a06f8caae7a1558311d59d83671d0c3d04064308e171a850")

addappid(3594600)
addappid(3594870)