-- generated by KeySteam
-- update time: 2025-01-20
-- app_name: Alien Arena: Warriors Of Mars

addappid(629540)

addappid(629541,0,"693bde1cd7a520b9c9c88ef0accb965c0d0c9de73624433aeca2d5832a79857e")

addappid(917170)
addappid(985130)
addappid(1004440)
addappid(1021170)
addappid(1097290)
addappid(1118510)
addappid(1181890)
addappid(1211860)