-- generated by KeySteam
-- update time: 2018-08-18
-- app_name: 寇莎梅特：困世迷情 Consummate:Missing World

addappid(630060)

addappid(630061,0,"ef307ae882451b79f9b06353d4c4449b85882ace7dd3cb75509001204274b2d2")

addappid(847470)
addappid(1153050)