-- generated by KeySteam
-- update time: 2021-03-22
-- app_name: Faulty Apprentice

addappid(630550)

addappid(630551,0,"5ceed683d9cedd786dec127c9fdb1be3ab065d23c0e4c65422e0e6e3e9cc38bb")

addappid(1021580)
addappid(1212690)
addappid(1268500)
addappid(1287760)
addappid(1288850)
addappid(1344610)
addappid(1393040)
addappid(1479110)