-- generated by KeySteam
-- update time: 2020-04-27
-- app_name: Akihabara - Feel the Rhythm Remixed

addappid(636740)

addappid(636741,0,"91912607a6bedbd20e33187a5f29af2e06a07a1ecbe894e9d3e93fe185a82d63")

addappid(976540)