-- generated by KeySteam
-- update time: 2025-11-12
-- app_name: Warstone TD

addappid(562500)

addappid(562501,0,"d07673051bf5c1a04a3dd26bc15448ed4a65be0486fd2cb9f7c39a72fde32060")

addappid(1225210)