-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: 三国志汉末霸业

addappid(577230,0,"43ee897087b5231758d95b8983edc9fd4008038379421c6ff71a28cd01e33d96")

addappid(577231,0,"9637d76aa413d336de9550b3932653ee37f71ac30d96721a9bcc5e14a87ec788")
addappid(577233,0,"9bb32a976cd5c911f2cf02d5251dc28fbce00f9a991701c09532e03cd630637e")

addappid(692770)
addappid(1150750)
addappid(1520720)
addappid(1863450)
addappid(2022570)
addappid(2350150)
addappid(2350160)
addappid(2718740)
addappid(3171550)
addappid(3575830)
addappid(4330990)
addappid(4331000)