-- generated by KeySteam
-- update time: 2025-10-29
-- app_name: Secrets of Salem: The Phantom Cab Collector's Edition

addappid(3855990)

addappid(3855991,0,"88688011b6196374f9c5d54eb0f92a1e68a01970d1ec36e9bd4abe2c73ed2d94")

addappid(3856310)