-- generated by KeySteam
-- update time: 2023-02-24
-- app_name: Punk Wars

addappid(1541790)

addappid(1541791,0,"aa8e37bfaf7af99143b1c3019149797e0cc5e6495f544940f5b15d53d995da2a")

addappid(1830660)
addappid(1932040)