-- generated by KeySteam
-- update time: 2025-10-29
-- app_name: Knightly Passions

addappid(1554260,0,"81a5dba293f3a7308ef58804e110b31f0c741604a50ea67c7ec2706b045a3618")

addappid(1554261,0,"f021768abc75d753fe480052bfb61d9e6cf6274bcab55b34a3ef65802c74e3cb")

addappid(2919800)
addappid(2933520)
addappid(3163410)