-- generated by KeySteam
-- update time: 2024-10-11
-- app_name: Wife Quest

addappid(1554600)

addappid(1554601,0,"c0a93fda0e71a078a9293ce6cf3015997cfb69f9ae137c84df2b7decf31cb43d")

addappid(1744540)