-- generated by KeySteam
-- update time: 2022-02-28
-- app_name: 魔女之泉3 Re:Fine －玩偶小魔女艾露迪的故事－

addappid(1592520)

addappid(1592521,0,"fc0ffe7dae93ed9a8c14a36d67a915b01ff4279f25bb874e351981804fdd8f42")

addappid(1753550)