-- generated by KeySteam
-- update time: 2026-02-19
-- app_name: Corsairs Legacy

addappid(1594880)

addappid(1594881,0,"ebfe05cf0ade7af896bef16008d81c8c4a69ed3d2c66f0e18830d18ec6575053")

addappid(2461620)