-- generated by KeySteam
-- update time: 2023-12-22
-- app_name: 舍伍德侠盗团 

addappid(1351000)

addappid(1351001,0,"b55b3a9859675e8cfccbb2c111ca9987ea4becee8654ea81f98cc17fa510172e")

addappid(2394550)
addappid(2432270)
addappid(2432271)
addappid(2432272)