-- generated by KeySteam
-- update time: 2025-11-07
-- app_name: Love Tavern

addappid(1354230)

addappid(1354231,0,"c2b04b2b62e2de8b09e24c7a617c5644599c023c70fc2ede9edf60d861771cf5")

addappid(1380590)