-- generated by KeySteam
-- update time: 2025-10-23
-- app_name: 谁想成为百万富翁？(Who Wants To Be A Millionaire?)

addappid(1356240)

addappid(1356241,0,"6e5b0f9cc211866c75cfc708e8e0746037ebbb60a6aecdfa24c1883bdfd8e67c")
addappid(1815670,0,"d444a35823093ffbdee460dee524e6e6143f5a89f0c3876afebcb2b9f3ff72e6")
addappid(2602750,0,"bf126a8b005b45a9beead3dcfc26c8dea172a8e40a00e0412a74f69e0608ad6a")

addappid(2635140)
addappid(2635160)
addappid(2635180)
addappid(2635190)
addappid(2635200)
addappid(2635210)
addappid(2635220)
addappid(2635230)
addappid(2635250)
addappid(2635270)
addappid(2635330)
addappid(2729730)
addappid(2873940)