-- generated by KeySteam
-- update time: 2023-03-27
-- app_name: STRANGER OF PARADISE FINAL FANTASY ORIGIN

addappid(1358700)

addappid(1358701,0,"882a9301f93fb1940dc1c638bf6f343c4c2513d29d3dd46fc5208976e9de966d")

addappid(2191870)
addappid(2252280)
addappid(2337570)