-- generated by KeySteam
-- update time: 2025-12-16
-- app_name: POSTAL: Brain Damaged

addappid(1359980,0,"17286d0795724b145c8496a2b2a3d6d756b0749964e7d4190945221c36fe4da0")

addappid(1359981,0,"4407b8f39b12b4d47ebb635bc862313dc9e3f5afe62b8cbbd0314223eead3856")

addappid(2015160)
addappid(3768390)