-- generated by KeySteam
-- update time: 2026-02-10
-- app_name: 牧场物语 来吧！风之繁华集市

addappid(2508780,0,"34db92710a920fab17ef00ef9f41849d414e79a09d8e173a8b5d17cf06a44893")

addappid(2508781,0,"d3d2cecbf425b32af43928d0b54fb991edc1a74dfac4d72d31a47b22d078ec14")

addappid(3051770)
addappid(3051780)
addappid(3051790)
addappid(3051800)
addappid(3051810)
addappid(3051820)
addappid(3051830)
addappid(3248040)
addappid(3406540)
addappid(3482230)
addappid(3847810)
addappid(3847820)
addappid(3847830)