-- generated by KeySteam
-- update time: 2025-01-14
-- app_name: 索尼克×夏特 世代重启

addappid(2513280,0,"e0abc9176e888d518a19c82d11ec21ee406caa5aa5d24404982feabdb9d16bba")

addappid(2513281,0,"e5b9cddfe91ed04af8c6d17537301797ab16a5041a7edca1d45ae281208a740f")

addappid(2909770)
addappid(2909780)
addappid(2909790)
addappid(2983600)
addappid(2999160)