-- generated by KeySteam
-- update time: 2024-09-16
-- app_name: The Legend of Legacy HD Remastered

addappid(2516220)

addappid(2516221,0,"46af2b2482af51cc318d5bbe40f2d2c1340f26195aff3ade3b15b58ec0319ccf")

addappid(2728870)
addappid(2733170)
addappid(2781930)