-- generated by KeySteam
-- update time: 2025-11-07
-- app_name: Sleepover: reWake

addappid(3961110)

addappid(3961111,0,"8f30650f9ac6f2fc9c986495cb3038e19fead796c0389e8ceafae2cec5ee5c90")

addappid(4070490)