-- generated by KeySteam
-- update time: 
-- app_name: Eco

addappid(382310)

addtoken(382310,"1153146306108996449")

addappid(382311,0,"3fbe09853da1a7ac7b1aa15652be1895746da18714c1807b011212858c982f51")
addappid(382312,0,"d0efd69c2526add85dbda57dd9dd17d97f284da29533e13a250a9b8ca031b2f0")
