-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: Empyrion - Galactic Survival

addappid(383120,0,"a39942a82da59705f1108e95029e392f323c4a624d51af16b39323d48ae3f96a")

addappid(383121,0,"34c1757941c6a2a64511d2d07327a24569014d7bd684b4259ec76f37f7aedc55")

addappid(2765930)