-- generated by KeySteam
-- update time: 2025-08-10
-- app_name: CPUCores :: Maximize Your FPS

addappid(384300)

addappid(384301,0,"da5a3e68c9ed912dc199160655f508a26739096a242cf275dce4ff6bafde0277")

addappid(726480)
addappid(736580)
addappid(842680)