-- generated by KeySteam
-- update time: 
-- app_name: Arma 3 Samples

addappid(390500)

addtoken(390500,"17746492832454752859")

addappid(390501,0,"5a27a4ab29a120a36d3939a1531f7070510781ee303a052c30616a301dfda0e7")
addappid(390502,0,"e8894cdc618b74429a4ba209a2a4b84bd88fb0a42770302bfca4c7abcf26c84f")
