-- generated by KeySteam
-- update time: 2016-10-06
-- app_name: NOBUNAGA'S AMBITION: Sphere of Influence

addappid(392470)

addappid(392471,0,"5f45e75de1f346139e23aa01161a4f06b5dccba1343bfdb88c642ad62c3ce700")
