-- generated by KeySteam
-- update time: 2025-12-27
-- app_name: 神州志西游

addappid(1449070,0,"417b4547231bb2f2dfcffa280f9851cd9bc7a43ff79be9504f8d7abb5d36f338")

addappid(1449071,0,"c456f9618b01e443fe6335403be2cb31891a949eac078764eb206fa5e6a63d79")

addappid(2502100)
addappid(2836380)