-- generated by KeySteam
-- update time: 2023-01-13
-- app_name: 饮料吧侍女 -回归-

addappid(1449330)

addappid(1449331,0,"ebb59ab7d79dda6561bd2f43ed2e93d2e2694c3df77bcce9dd1e1fb253274fe0")

addappid(2295330)