-- generated by KeySteam
-- update time: 2025-01-30
-- app_name: 盗日求生：撤离

addappid(1456940)

addappid(1456941,0,"b27ec4f913bc6089773b4bed8aa18bd1103bed28d9c304cf957aba343f09ee08")

addappid(3110340)
addappid(3126940)
addappid(3142390)