-- generated by KeySteam
-- update time: 2023-01-29
-- app_name: Kiss Effect

addappid(2288480)

addappid(2288481,0,"7dc6ce02ace230185492be138e8c98d53446f2f9bfb781c5737bdfc89ee7925c")

addappid(2295620)