-- generated by KeySteam
-- update time: 2024-12-26
-- app_name: 傲慢的怪兽公主与名侦探使魔

addappid(2291680)

addappid(2291681,0,"d5f249db247fe7b9d64a53304732e9775a8ffc470308d03c4e96fc84f8775f71")

addappid(2714820)