-- generated by KeySteam
-- update time: 2021-01-02
-- app_name: Your amazing T-Gotchi!

addappid(1420740)

addappid(1420741,0,"61b8e36380f44fd963d80755dc9a469f4d65e21444e827bde69a3a0a7dbcbe36")

addappid(1580360)