-- generated by KeySteam
-- update time: 2021-07-17
-- app_name: 爱与战争：天选英雄

addappid(1433420)

addappid(1433421,0,"485f83a6148c298e5597c867aa560d8fb0a03f3080ae78b9abf98ef631913362")

addappid(1434450)