-- generated by KeySteam
-- update time: 2026-02-02
-- app_name: 雨世界

addappid(312520,0,"ef800a2479027ef2829d53f0c9cccd74da5c5f7fa82e5bb626c069cd07cd2b99")

addappid(312521,0,"f36b23dfaca5b387508e33fe17732bcd48a16ab0fef3b1eb819494ad76d5ce2a")

addappid(1933390)
addappid(2857120)