-- generated by KeySteam
-- update time: 2024-07-08
-- app_name: RPG Tycoon

addappid(314240)

addappid(314241,0,"5e795f08b570543d81ab5c33b2cec53917ca853b281084808accc6c3db223cc2")
addappid(551250,0,"3c67959683a7798edd63e42533db5c4acee014e990afb467eada713e19cbb1f4")
