-- generated by KeySteam
-- update time: 2025-07-19
-- app_name: 山的桃源乡，海的乌托邦

addappid(1261220)

addappid(1261221,0,"1f8fe8b95d94044f2786221da0cccf43154444ae695184ae85ce0b07b70ee1a1")

addappid(2229290)