-- generated by KeySteam
-- update time: 2020-12-22
-- app_name: Last Fantasy Hentai

addappid(1263780)

addappid(1263781,0,"6706fa47cf886015cce5cbf6c47e55150f94b28a56ea06505bc4c3a62c8c0d70")

addappid(1356510)
addappid(1454120)
addappid(1824030)
addappid(1828230)