-- generated by KeySteam
-- update time: 2020-10-25
-- app_name: Adorable Crush

addappid(1266800)

addappid(1266801,0,"4ef1b0a2f158c7be05d8931db1f56fcd106c126b082d1ee3fdb383cf16a899b4")

addappid(1368920)