-- generated by KeySteam
-- update time: 2025-10-16
-- app_name: ISEKAI QUEST

addappid(1268110)

addappid(1268111,0,"2cc27adba9ed2e1ae7f47091e6f5d5cdfdcc1bcaa71aa027041b7e78d6ee3d4c")

addappid(1398050)
addappid(1398060)