-- generated by KeySteam
-- update time: 2024-10-29
-- app_name: 死亡约束

addappid(1277130)

addappid(1277131,0,"f0e25285c69f852068c19218ffc7cf08b44abe1d4f922bb637a77fc5e068e9c9")

addappid(2936870)
addappid(2990150)
addappid(3010570)