-- generated by KeySteam
-- update time: 2026-02-20
-- app_name: FPV.SkyDive

addappid(1278060)

addappid(1278061,0,"24007944eeceda09e4a71a068a2eefb61e0796774810ea33b1e769d2eb523cd3")
addappid(1278064,0,"85f5cc3514685e06ae8036612ff2e9586dc1a3aba9ddb6d7e36dc0f69022aa74")

addappid(1838190)
addappid(1966060)
addappid(2376830)
addappid(2384660)
addappid(2511190)
addappid(3007600)
addappid(3896940)