-- generated by KeySteam
-- update time: 2025-10-15
-- app_name: Vampire: The Masquerade - Shadows of New York

addappid(1279630)

addappid(1279631,0,"647aeaae509b7b2774fe9aadb85a0f949e8a0782bb99d1b175f23d0aa4538d8d")

addappid(1405990)