-- generated by KeySteam
-- update time: 2026-02-10
-- app_name: MechWarrior 5: Clans

addappid(2000890)

addappid(2000891,0,"2e57d475d5e205a6ad926d2b6817b2585d9698098c141a54af8e60e6489bb444")

addappid(3170420)
addappid(3170430)
addappid(3323880)
addappid(3463200)
addappid(4128140)