-- generated by KeySteam
-- update time: 2026-03-25
-- app_name: 后汉稽异录

addappid(2010900,0,"cce0acee2c0f12ea1b7d1a6a7cd169f08020295fc7aa4e3fec0ff8688904b65c")

addappid(2010901,0,"c3f53ddfca46d00c2c3f9d50d36167d936c18e55cab77e90133bfb10aaf9ee2f")

addappid(2674440)
addappid(2694320)