-- generated by KeySteam
-- update time: 2024-11-26
-- app_name: FIGHTING GIRL SAKURA-R

addappid(2013060)

addappid(2013061,0,"9a46acb239c565e04080575e871594f9723c72811d74c00816320dabecd772d6")

addappid(2013520)