-- generated by KeySteam
-- update time: 2023-10-10
-- app_name: LIVE A LIVE

addappid(2014380)

addappid(2014381,0,"7fda95293f7806c84dd40f809c1ec537ad42ad31989ceb136bd9815b627341d7")

addappid(2378630)