-- generated by KeySteam
-- update time: 2026-03-16
-- app_name: 风暴崛起 Tempest Rising

addappid(1486920)

addappid(1486921,0,"26528db8fe19a223ddd4dbc280b52006e6b4aad5884ce084762e313c91d0de46")

addappid(3478250)
addappid(3478280)
addappid(3710570)