-- generated by KeySteam
-- update time: 2025-03-25
-- app_name: 战争交响曲：尼菲林传奇

addappid(1488200,0,"1bb036cb23ee650102dc8443e9eb7060089ef6c687dc47871549ce5ead8babc0")

addappid(1488201,0,"cb108864285e7a1c1b19d7f44f9eecd18b88b0d304f6f8caa93e55dca7e54588")

addappid(1999620)
addappid(2432430)