-- generated by KeySteam
-- update time: 2025-10-30
-- app_name: Operation Night Strikers

addappid(3099790)

addappid(3099791,0,"e02c473932bce6249c7fb6c4ada54e7e2ee0730b7278a0a1fd9ee2ceffa55bf9")

addappid(3380600)
addappid(3837630)