-- generated by KeySteam
-- update time: 2025-04-03
-- app_name: EDENS ZERO

addappid(3125750)

addappid(3125751,0,"8e98d35380e0ac080fbc6342eca2d99a14165fb1f54e883ecf81a691c99c1ecf")

addappid(3273490)
addappid(3345380)
addappid(3345400)
addappid(3345410)
addappid(3345420)