-- generated by KeySteam
-- update time: 2026-03-18
-- app_name: Legacy of Defense - 防御遗产

addappid(3135200)

addappid(3135201,0,"5bdcd70ca53e92ad415e84d190f09456613f4428fb457985c6db88d6afbfe4f7")

addappid(4032960)