-- generated by KeySteam
-- update time: 2025-05-28
-- app_name: Baradroid - A Gay Visual Novel

addappid(1952750)

addappid(1952751,0,"49735acb46216acd3dfafb22093eaa57c1e149a4b92bfe7a59257d4f0f138e77")

addappid(1959310)
addappid(3043060)
addappid(3043070)
addappid(3122520)
addappid(3749520)