-- generated by KeySteam
-- update time: 2022-07-03
-- app_name: Seven Deadly Dates

addappid(1953490)

addappid(1953491,0,"8c17625f82e2782e82e42e4cc0a4157bccb0c75aec47f57d77e757318b8c3f84")

addappid(2074210)