-- generated by KeySteam
-- update time: 2025-09-29
-- app_name: 东方冰之勇者记

addappid(1955830)

addappid(1955831,0,"7c520a8442f3537e7006593708adc76ceb19a2a0bdb9ad6a1158ad9d5c570dad")

addappid(2302890)
addappid(3213970)
addappid(3858250)