-- generated by KeySteam
-- update time: 2025-01-22
-- app_name: Night of Love

addappid(1957130)

addappid(1957131,0,"a082933d051d8fa25e343a4d1ee196c9fabaa56d8f0ceeec8f2d05732eaa7d75")

addappid(1962480)