-- generated by KeySteam
-- update time: 2025-08-19
-- app_name: 赫雷斯的角斗场 Ⅲ

addappid(2875610)

addappid(2875611,0,"639beb8000cf0f91a72c541607879687e6f4dfc8821d5a01d3edfd3ceeebcf89")

addappid(3709910)