-- generated by KeySteam
-- update time: 2025-10-12
-- app_name: College Kings - The Complete Season

addappid(1463120,0,"7be82f51205d0a0cd0eb695f6d2a166b09d08bff796845bf41c1bc222bab1c6d")

addappid(1463121,0,"028021ea8aaaaea17bfede62ddd261a646c576dea9c46cacbcd786f967eb3cd5")

addappid(1624520)
addappid(1732640)
addappid(1847490)