-- generated by KeySteam
-- update time: 2025-08-22
-- app_name: 白昼梦・心象病院

addappid(1465710)

addappid(1465711,0,"ae31ebb877574ad2eb3cefc1e960c4fffe0257bcc29cd99d9009780d924437d5")
addappid(1465712,0,"502d1f027f302102c2f66a87ce8a0871c3a4c2f20fb07abc77a61923861357a2")

addappid(2754310)
addappid(2754320)
addappid(2754330)