-- generated by KeySteam
-- update time: 2024-11-24
-- app_name: Button Lock 2: Star Carrier

addappid(1479360)

addappid(1479361,0,"8be5c2fcd8c00a409967f2f026d38818c8ca9f050462980c9265ce674b208f98")
