-- generated by KeySteam
-- update time: 2023-03-14
-- app_name: Voice of Cards: The Forsaken Maiden

addappid(1748660)

addappid(1748661,0,"c0c07258d6f9301adf7b6c572a905205b5746d9f46c9c68903b30e59a7673163")
