-- generated by KeySteam
-- update time: 2025-03-21
-- app_name: Land of the Vikings

addappid(1981570,0,"deda2919d13e947d72d5a79a817850224f56848c617298f50e08ba1ae3997ecb")

addappid(1981571,0,"a1b41c1b70dfae9a260b2dd2641088e54a61bce753248a76e247ae96f7537f68")

addappid(2997370)
addappid(2997380)