-- generated by KeySteam
-- update time: 2022-06-07
-- app_name: 打字游戏：十二生肖女孩的秘密

addappid(1983600)

addappid(1983601,0,"5755389dbee69004e261222fe1c995fcf13f5f3120549b5bda46228b1e40d60d")

addappid(1991800)