-- generated by KeySteam
-- update time: 2022-08-02
-- app_name: 打工吧！天使酱 ~天使在魔界的劳改生活~

addappid(1984350)

addappid(1984351,0,"88c1b742c0a24f49d4d24a2895c1847e7b3639538250a1b3735c1b349355c610")

addappid(2095550)
addappid(2095551)