-- generated by KeySteam
-- update time: 2025-06-28
-- app_name: Hentai Stories

addappid(2642820)

addappid(2642821,0,"c4a8b7f6b8019817b6ce6fcb86624bf6ea1d976cfeac490b1f17c6f544af011d")

addappid(3430220)
addappid(3430230)
addappid(3430240)
addappid(3679360)