-- generated by KeySteam
-- update time: 2024-07-06
-- app_name: Star Trek: Resurgence

addappid(2653940)

addappid(2653941,0,"ee1cbdec40a1fad0b1834e8c18dc966cbbb2adabda6f1583968128b37b4faf16")

addappid(2979360)