-- generated by KeySteam
-- update time: 2025-11-26
-- app_name: 末日地带2

addappid(2144640,0,"7ca07b384ee60a80dd525456c888cf96619c7dad0c985f1d3fc0ec77c2ebeb9c")

addappid(2144641,0,"0a49695ed1feda3f6ad84629f01e5139b5793585af34810d1dbd600c5236c9bf")

addappid(3124440)
addappid(3142480)