-- generated by KeySteam
-- update time: 2026-02-02
-- app_name: The Seven Realms: Terran

addappid(2154330,0,"1e235efe4edea111ae95775cbb89fe1b224e24accae6cb2c7432104900b1c73f")

addappid(2154331,0,"301400af25781cf3689238601d5557b04a6df2cc65971d4da3ae48d5fd2b4ae3")

addappid(2211370)
addappid(2368280)
addappid(2385380)