-- generated by KeySteam
-- update time: 2026-02-20
-- app_name: The Mystery Of Woolley Mountain

addappid(521560)

addappid(521561,0,"a51af15fee7d93bcb774d7b92917c0fc3359f46aac16d2e757d4b24018f2f0bc")

addappid(1264780)
addappid(1883900)
addappid(2913960)
addappid(2913970)