-- generated by KeySteam
-- update time: 2017-11-24
-- app_name: Asura: Vengeance Edition

addappid(524640)

addappid(524641,0,"a359b6e92f845e64556585e6d6cff009bd43e4079ab6f5fe26f8b0e0f8ba967b")

addappid(584630)