-- generated by KeySteam
-- update time: 2019-10-30
-- app_name: 東周列萌志 Philosophic Love

addappid(528060)

addappid(528061,0,"c7ff98bb4a5f53401b2b5d7fc386271ca6e0d009cee92c9481664f73fff38c0f")
addappid(528062,0,"0bf68fcc926b076c82f73962b472d80374ffe3093e0bf8316e2c93313b3106b7")
addappid(528065,0,"5857fd2ea6152624f5959a977ae92b42b70a5e65886beb3870b02577c96c4018")
addappid(528066,0,"eea6bcbea0fb388e2ae4ae2efff1f4d6af0564c5276bb1c834dc53eaa8688467")

addappid(894500)
addappid(895130)
addappid(1249920)