-- generated by KeySteam
-- update time: 
-- app_name: 巨塔57

addappid(530950)

addtoken(530950,"6777079248721983875")

addappid(530951,0,"640924741d40576b7bba0927460a4b7a3d7e938e9d2a8dca642696e1262b8861")
