-- generated by KeySteam
-- update time: 2017-04-30
-- app_name: Tornuffalo

addappid(534720)

addappid(534721,0,"032635a47bf4373636b8031ff19fd80147496d3165f13487b19ad2c1149c99f2")

addappid(574730)
addappid(622110)