-- generated by KeySteam
-- update time: 2018-07-04
-- app_name: Heroine Anthem Zero

addappid(537990)

addappid(537991,0,"774ee05d0b1c40c22921b3766f49d1a171db712d92fb35379ce54d1394f4d406")

addappid(571670)
addappid(609200)