-- generated by KeySteam
-- update time: 2017-01-06
-- app_name: 十二色的季节

addappid(370280)

addappid(370281,0,"27089ed26388824334ff3fe631fa6fead2e68f1adb006fcb9db794091b6a6643")
addappid(370282,0,"230ba23f95f17be56c7a6d9f3797693f9b4ddf8eab9707f79f8cb81ab188b168")
