-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: 終天教団

addappid(3216500,0,"b77eb496770278f0167f0497c7a96405fde936657548b634f11bec77c96fce7f")

addappid(3216501,0,"dc2a9f945722661f9ae1e59db7468dfdb8ec05e296b74c91b03ba7f8fa04985b")

addappid(3662610)
addappid(3830900)