-- generated by KeySteam
-- update time: 2026-01-22
-- app_name: 电车解题

addappid(3219410)

addappid(3219411,0,"a31e949b85e01622dba80a2ffee946a43f1b54e9a97505c7b92d1ee9814c2259")

addappid(3550600)
addappid(4389630)