-- generated by KeySteam
-- update time: 2024-01-19
-- app_name: Coffee Talk Episode 2: Hibiscus & Butterfly

addappid(1663220,0,"65115854105a46e1b5d0e00f57bcfb14c57da5a12d36a4e385b37d49032f88a2")

addappid(1663221,0,"f7a1de289cb5e297e44b260552832891eae292ff39e9928f178384b65a7b0dc8")

addappid(2184540)