-- generated by KeySteam
-- update time: 2024-12-09
-- app_name: The Legend of Heroes: Trails to Azure

addappid(1668520)

addappid(1668521,0,"7ff8469ddb0a97bf177dca7527ef140b913e1760b8b518d5c33d2c4ff6d83991")

addappid(2318450)