-- generated by KeySteam
-- update time: 2026-03-24
-- app_name: 主权辛迪加：雾都疑案

addappid(1674920)

addappid(1674921,0,"b5853a28eefabc5c5aeab14987cbea90a10f1c1b9947455390d98d0febb67b89")

addappid(2748380)