-- generated by KeySteam
-- update time: 2025-09-23
-- app_name: Euryale's Gambit

addappid(1674180)

addappid(1674182,0,"6ab5349b76f75da8b0a894b2a9a60114df4190c87e4831dd4d5c271ba06360c6")

addappid(1856320)