-- generated by KeySteam
-- update time: 2025-11-18
-- app_name: The Case of the Golden Idol

addappid(1677770,0,"b908b4345ce9f6ee7a85d089245b8554fddb471a2bd6d953e56de2cba9a9c53f")

addappid(1677771,0,"0e6df5386d3edab1de6917c178f5e71e68bf11511a9895a7d7dc7ee85dbf5ffa")
addappid(1677775,0,"27ec2f00c0a16576c3a95bb0717af8df5a20f79d7d2194aa4de4e84d34f901c3")

addappid(2377000)
addappid(2377001)