-- generated by KeySteam
-- update time: 2025-12-23
-- app_name: 苏丹的游戏

addappid(3117820,0,"5b953b3aff2ae34d4eee90a135eaee5a3e1377be9a5c4c6af9c218072aff7589")

addappid(3117821,0,"6da5c61617ae1bce4dec442e070762a2b581103f5765d3067a24cc1276dd0461")

addappid(3728320)