-- generated by KeySteam
-- update time: 2025-12-19
-- app_name: 绯红编年史 ~ Chronicle of Scarlet ~

addappid(3117660)

addappid(3117661,0,"07a06331b69cb1be784260ab6b9b13dd332e322e360c45a68229086cdb301eae")
