-- generated by KeySteam
-- update time: 2017-12-07
-- app_name: Astebreed: Definitive Edition

addappid(283680)

addappid(283681,0,"7f6bf8bdaabd54b84f7cc819600e938825736736627d92ecfd174915f12a6dfe")
