-- generated by KeySteam
-- update time: 2024-10-08
-- app_name: BoneTown

addappid(288080,0,"1127cd81d8f784ab564b3d499c31077a0d9681efeed881770cc8a20489c721e5")

addappid(288082,0,"5f22d0bf8b0e5f6406e83e97193e036d10f13596cce7c1efc60b2648ac4016e7")

addappid(1668100)
addappid(2466570)
addappid(2963010)
addappid(2963030)
addappid(2963040)
addappid(2963050)