-- generated by KeySteam
-- update time: 2025-08-08
-- app_name: Yoshima: Hentai Simulator

addappid(3298250)

addappid(3298251,0,"656439b90e74c833bd5ea954098b00a4302212400ba7c93147741dff3981f4bc")

addappid(3491040)
addappid(3491050)
addappid(3493710)
addappid(3650570)