-- generated by KeySteam
-- update time: 2024-11-06
-- app_name: AURA: Hentai Cards

addappid(2440200)

addappid(2440201,0,"6dbc7e13591d109bd45665429c0863f0f95df37f15196a6ee1668330bb03de29")

addappid(2614170)
addappid(2614180)
addappid(2685560)
addappid(2723440)
addappid(2814050)
addappid(2960450)
addappid(3188410)