-- generated by KeySteam
-- update time: 2026-02-25
-- app_name: 爱与生活：幸运老师

addappid(2445340)

addappid(2445341,0,"abd0d78162f8690db2b855ea021f3a15eef0d8150644b9a529e5fb3aaa21d326")

addappid(2662040)
addappid(3216840)