-- generated by KeySteam
-- update time: 2026-03-24
-- app_name: 夏日美女：欧巴请和我恋爱吧！ 

addappid(4179020)

addappid(4179021,0,"35ee1078d5d6394d65a30a04aa000fb8763a59b0864b0f6175ab238cc27a36ac")

addappid(4416280)