-- generated by KeySteam
-- update time: 2022-09-01
-- app_name: Space Ribbon

addappid(501220)

addappid(501221,0,"616a7c2f8c1a39fff8268a684aa7bb6cd0c371000f4fa89f6f96ad1346bba7e4")
addappid(501224,0,"99f5ec469117408e5942352d120d75b046f1678a237a3505b0b580b98aaeedd9")

addappid(512970)
addappid(543640)
addappid(543660)