-- generated by KeySteam
-- update time: 2026-02-10
-- app_name: Eximius: Seize the Frontline

addappid(505740)

addappid(505741,0,"ae216fe11797106d35ecfb02882c3c9c1c7b1d435c7816b8bf5741bfe15962cd")

addappid(1576310)
addappid(1576311)
addappid(1576312)
addappid(1723520)
addappid(1723521)