-- generated by KeySteam
-- update time: 2020-05-18
-- app_name: 根神京姬 后篇

addappid(701420)

addappid(701421,0,"b145311a5a3bdd485d3ee149f9eadbdee9aacc0b8542b6e0cd4156666e320f7a")
addappid(701422,0,"07eb1c3e0199b2f4e1aae5ef8ccffc440408c7346cfc94acf1e01cd0db0bdbcb")

addappid(845340)
addappid(947760)