-- generated by KeySteam
-- update time: 2025-08-18
-- app_name: Clarent Saga: Tactics

addappid(709670)

addappid(709671,0,"56e37efb9f145ddac3b061ce08021f04b88ae9876be30dbcc5f401c10f1a6291")

addappid(1602640)
addappid(1602641)
addappid(1602642)
addappid(1602643)
addappid(1602644)
addappid(1603010)