-- generated by KeySteam
-- update time: 2025-10-07
-- app_name: 《密教模拟器 (Cultist Simulator)》

addappid(718670,0,"330e56718beb0870998bd42ad67b000888f9623075f7493a163f2a8671e3a159")

addappid(718671,0,"dc20d4bf29f7456c029b2098de8aa019810ec20323584afbc2cf84842b23d713")

addappid(871650)
addappid(871651)
addappid(871900)
addappid(874050)
addappid(1259930)
addappid(1813090)