-- generated by KeySteam
-- update time: 2020-01-18
-- app_name: Hentai Cosplay USSR

addappid(1223250)

addappid(1223251,0,"04c5815f9fbd875197c1308e3338d3bf140005e27349ddc70006ff0b94b83551")

addappid(1230970)