-- generated by KeySteam
-- update time: 2022-09-30
-- app_name: Lotus Reverie: First Nexus

addappid(1227570)

addappid(1227571,0,"9581f9a4bc8e847cc78e7cd6d0f1cd82d839484adc763ada7044a8dfa23c8f1c")

addappid(1317180)