-- generated by KeySteam
-- update time: 2025-12-10
-- app_name: Knock on the Coffin Lid

addappid(1232580)

addappid(1232581,0,"32718d93ad2804ff032dfb35bdbcd1b786c02ed19a8e40fec6ead1248c34f692")

addappid(1608610)
addappid(2891150)