-- generated by KeySteam
-- update time: 2025-01-24
-- app_name: 索尼克 未知边境

addappid(1237320)

addappid(1237321,0,"9c57e01f36d7bf7a77b07678b08a0e690d785dfbcd9a421ae1fc2157741b5ccd")

addappid(2079300)
addappid(2079301)
addappid(2089730)
addappid(2089733)
addappid(2089840)
addappid(2093240)