-- generated by KeySteam
-- update time: 
-- app_name: 薄暮夏梦

addappid(1323830)

addtoken(1323830,"5446874793346998862")

addappid(1323831,0,"2a6049716831049f8ee162a4760b3cdbe37dd7c57c6f1cab929f01c6d2948fc8")
addappid(2867941,0,"0f403113218dfca7c13ab60f869388b28bdadf260f5db6c50a4a85a391c3c47e")
