-- generated by KeySteam
-- update time: 2026-02-25
-- app_name: Easy Red 2

addappid(1324780,0,"9c2fd69454514ddde97c26fb0212ca728b182427f101e9d4f5cdf8ac40462f29")

addappid(1324781,0,"8a121832d20574941b7d7e7eb4a34323c9ebe72338fc859080aac679b74bd78c")

addappid(1888350)
addappid(2317930)
addappid(2617770)
addappid(3499380)