-- generated by KeySteam
-- update time: 
-- app_name: VTube Studio

addappid(1325860,0,"ad9abe0f7b6a080c36156a0919efbb7590ba2def7a3fe2e4bded4c26c336209d")

addtoken(1325860,"3339220585653284798")

addappid(1325861,0,"c2fcacf59a1d77f958a595fcac5654fdbff87a008e3563e7ef6dbd9423af176a")
addappid(2178540,0,"3a79a1e27e8a6e7133075fa19dafb01e35011fdff0a70fee9fc4a4d9152bc7f1")
