-- generated by KeySteam
-- update time: 2022-02-17
-- app_name: Wordle

addappid(1334000)

addappid(1334001,0,"3edbcc88cb31549eee0530cea827d19408fdeaa8344d223ce52c79269b37d4d7")

addappid(1532570)
addappid(1532580)
addappid(1532610)
addappid(1532630)