-- generated by KeySteam
-- update time: 2026-01-19
-- app_name: 风暴之城 Against the Storm

addappid(1336490)

addappid(1336491,0,"c62157594f44e2a3087998f70ca9dfe4736a0a98d9d1eca658ecaaf102f17dec")

addappid(2712950)
addappid(3075500)
addappid(3725110)