-- generated by KeySteam
-- update time: 2021-11-01
-- app_name: Treasure of Cutuma 3rd

addappid(1339670)

addappid(1339671,0,"775fe9e563e598488a164e5094a24a758ad8e84ae1663df9986be52f7c5c3eeb")

addappid(1379280)
addappid(1428990)
addappid(1477740)
addappid(2027150)