-- generated by KeySteam
-- update time: 2025-09-17
-- app_name: 兽设格斗前传：上

addappid(1620100)

addappid(1620101,0,"ed57aa5e42b928a89fc6e4f1a1c7093091b0dcd47cfd23b6d61592f4e17fb635")
addappid(1620102,0,"dceaea31a48c523e54804cdb5c742aa3d45353d5f5e92ea5bfbb32658ee4b25d")

addappid(2023110)
addappid(2140220)
addappid(2196880)
addappid(2196881)
addappid(2268920)
addappid(2309860)