-- generated by KeySteam
-- update time: 2023-02-15
-- app_name: 苏菲的炼金工房２ ～不可思议梦的炼金术士～

addappid(1621310)

addappid(1621311,0,"7efa5dc2c1f058948f98a3e2b75be10a0cf423134af8a02f79e9f78dc4602157")

addappid(1754680)
addappid(1754681)
addappid(1754682)
addappid(1754683)
addappid(1754684)
addappid(1754685)
addappid(1754686)
addappid(1754687)
addappid(1754688)
addappid(1754689)
addappid(1754690)
addappid(1754691)
addappid(1754692)
addappid(1754693)
addappid(1754694)
addappid(1754695)
addappid(1754696)
addappid(1754697)
addappid(1754698)
addappid(1754699)
addappid(1754700)
addappid(1754701)
addappid(1754702)
addappid(1754703)
addappid(1754704)