-- generated by KeySteam
-- update time: 2024-01-22
-- app_name: 爱与战争：天选英雄Ⅱ

addappid(1627680)

addappid(1627681,0,"213a60478bd35f3e62f84e79a925d368c4ea4986597d5c4ce33fe9d5ad5c1324")

addappid(1809620)
addappid(2311640)