-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: Steam Linux Runtime 3.0 (sniper)

addappid(1628350)

addappid(1628351,0,"34d2f12079df06725c158782f1ce1db27ba66c6dd9f5610a901fcc7dd5b9bcae")
