-- generated by KeySteam
-- update time: 2026-03-25
-- app_name: 星际裂变 (StarRupture)

addappid(1631270)

addappid(1631272,0,"cbb99a831607efa2d9529979e09ca1e3b1692bf978684330d6db62a558c30b52")

addappid(4167250)