-- generated by KeySteam
-- update time: 2025-03-19
-- app_name: Dome Keeper 穹顶守护者

addappid(1637320,0,"51edc2419db29d00f4bf8e8b6b50218f85587bc2fa34483df694efa4e3e854b4")

addappid(1637321,0,"c0d4d6c5d92ae7a0c63de34717961fde6f236bb14016e43c90d87efc92b5f5c8")

addappid(2152440)
addappid(2380060)