-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: Steam Linux Runtime 2.0 (soldier)

addappid(1391110)

addappid(1391111,0,"8c0894de187f61e472607bbb2763b8f3195bc050763b506fe829b70baf9040af")
