-- generated by KeySteam
-- update time: 2019-11-27
-- app_name: Depression The Game

addappid(881920)

addappid(881921,0,"f2e75ff5600dd371de1f62672dc24c8bbe6f43ac941e7a3174ff4285bf78bbe2")

addappid(1089410)