-- generated by KeySteam
-- update time: 2021-11-22
-- app_name: Four Kings One War

addappid(883680)

addappid(883681,0,"6f269f6cb92e0fdccfdde7b24fc800d4e4aeb89b2159923751427d736aa860f2")

addappid(932600)