-- generated by KeySteam
-- update time: 2021-01-04
-- app_name: Beat the Song

addappid(894340)

addappid(894341,0,"38b059e5f405f27f32857f13e099dfe5f3ebdc1ffc29ee78a223a2241c816575")

addappid(943750)
addappid(944870)
addappid(944950)
addappid(944970)
addappid(944980)
addappid(945000)
addappid(945020)
addappid(945040)
addappid(945080)
addappid(945120)
addappid(945130)
addappid(945170)
addappid(945180)
addappid(945200)
addappid(945230)