-- generated by KeySteam
-- update time: 2019-03-16
-- app_name: A Piece of Wish upon the Stars

addappid(899190)

addappid(899191,0,"da6d39266bdfc475b5df12a61a9aad7f96509730fec43015ee24ee0445ee7013")
addappid(899192,0,"9e084011331f3949df07979ae9623df32831fa843a81adb6358d73e12b73a17a")

addappid(972860)
addappid(972870)
addappid(972880)