-- generated by KeySteam
-- update time: 2025-01-30
-- app_name: Forever To You!

addappid(1609010)

addappid(1609011,0,"6ba02f4c1edcf68684ba00bc062ab97cb6b0ab7ceb1564816387b2c771b2c0b9")

addappid(2173560)
addappid(2654060)