-- generated by KeySteam
-- update time: 2026-03-13
-- app_name: 大巴扎 The Bazaar

addappid(1617400)

addappid(1617402,0,"e324353bb453459d674c0ff0a818181b8ab9f2fc5ec833e6fb278cd246806ff2")

addappid(3884450)
addappid(3884460)
addappid(3888890)
addappid(3888900)
addappid(3903660)
addappid(3903670)
addappid(3903680)
addappid(4082620)
addappid(4418930)