-- generated by KeySteam
-- update time: 2024-03-09
-- app_name: Tailbound

addappid(2130000)

addappid(2130001,0,"d2e98d594111b64f9da0b8503610f9748b81089c2c17b0a105be8cce3bb7d1a9")

addappid(2130150)