-- generated by KeySteam
-- update time: 2025-12-18
-- app_name: 东方凋梦录 ~ Fading illusion

addappid(2132480)

addappid(2132481,0,"bbbc6e6d4e06bd01daf072c0bfd4da1cbdea370f4bc3901e0fc7e5ac704d3529")

addappid(2865880)
addappid(3095760)