-- generated by KeySteam
-- update time: 2025-05-19
-- app_name: Skelethrone: The Chronicles of Ericona

addappid(2139840)

addappid(2139841,0,"8e5a3c405ffabd82d236d99d5583d2b3836f045da51e2328b307e3001f8c5977")

addappid(2917800)
addappid(3499570)