-- generated by KeySteam
-- update time: 2024-08-19
-- app_name: 神奇英侠 Capes

addappid(2081080)

addappid(2081082,0,"1df105e1632e8d7e1c2fd4604d3608934ae33cd7df6589b0c97972d4d761ea3c")

addappid(2348010)