-- generated by KeySteam
-- update time: 2024-04-06
-- app_name: Jam Scrapz Collection

addappid(2097480)

addappid(2097481,0,"20434b1814d5c487fb11291774005a005ebb518a14093fb7fcadaabc98167166")

addappid(2099160)
addappid(2099161)
addappid(2099162)
addappid(2099163)
addappid(2099164)
addappid(2278040)
addappid(2664740)
addappid(2664750)