-- generated by KeySteam
-- update time: 2023-01-09
-- app_name: Axiom Alternative II

addappid(1645620)

addappid(1645621,0,"49b1c2f3aa1cbfb203243c1c8411c7a503c85bdeb9275d0a13afab9e2b644fff")

addappid(1666730)
addappid(1666731)
addappid(4041390)