-- generated by KeySteam
-- update time: 2026-01-15
-- app_name: 修仙立志传

addappid(1649730)

addappid(1649731,0,"b1f84051977044c0ca948f11298f7dff38f2f61e6965b33ca61a135770d24225")
addappid(1649732,0,"b318c8c28a77d6aee5741bb0ca5ec9667d84778c62dfd6d21aa1392c8671920a")

addappid(2426820)
addappid(2811350)