-- generated by KeySteam
-- update time: 2023-01-11
-- app_name: 冒险者莉兹和情色迷宫

addappid(1652220)

addappid(1652221,0,"f30885c22f648ef8af161d5a7520c5b750d327c3bdbc973d3da7fc26dcde702a")

addappid(2260810)