-- generated by KeySteam
-- update time: 2023-01-11
-- app_name: 召唤师莲和情色迷宫

addappid(1653030)

addappid(1653031,0,"8a1dfabb9ff0e28157ecaad1bf24a34348cb46afdcb59490d3d5f169eac91a71")

addappid(2268530)