-- generated by KeySteam
-- update time: 2023-05-19
-- app_name: Figurine Scene Simulator

addappid(1659810)

addappid(1659812,0,"bd8048cd7e90fd9b4756bc5264cb2210eed09b3f78d3037b20147b28c5149efe")

addappid(1736100)
addappid(1736102)
addappid(1736103)
addappid(1736104)
addappid(1799344)
addappid(1799345)
addappid(1799347)
addappid(1835280)
addappid(1835281)
addappid(1872260)