-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: College Kings 2 - Episode 1

addappid(1924480,0,"f048019fe71318aed87be5d22f452089e0cee6112c3a975c5cc813afa927d60b")

addappid(1924481,0,"ff635112056ca80dc0760a59372d872768946344dc5d10a5e63676f081245cf7")

addappid(1929620)
addappid(2100540)
addappid(2141200)
addappid(2141201)
addappid(2164670)
addappid(2267960)
addappid(2725540)
addappid(3126690)
addappid(3780980)