-- generated by KeySteam
-- update time: 2024-01-05
-- app_name: 姦控の器

addappid(1928500)

addappid(1928501,0,"2b4afb5de6b383c8c84de0b01005ac29cf2bb0d09b2daab7ec05c2c2410cb076")

addappid(1933710)
addappid(1933720)