-- generated by KeySteam
-- update time: 2025-12-13
-- app_name: 提早绽放的黑百合

addappid(1931940)

addappid(1931941,0,"5de0d1aff90ed053bf408479f5e5ee0e4dc74b6d10aa97c7bb289b0d47c08648")

addappid(1951010)
addappid(1951090)
addappid(1954430)
addappid(2697130)
addappid(2869360)
addappid(2869370)
addappid(2869380)