-- generated by KeySteam
-- update time: 2023-08-07
-- app_name: Neptunia: Sisters VS Sisters

addappid(1932160)

addappid(1932161,0,"3335c0fd172d4ff643c469013cae0e956bc0603185df4999b5e57e3115fe1d6c")

addappid(2111700)
addappid(2111701)
addappid(2111840)