-- generated by KeySteam
-- update time: 2025-12-19
-- app_name: Simon the Sorcerer Origins

addappid(1939890)

addappid(1939891,0,"DBE7CCC84527065514A5D7D1D47B94A4F7754CE6154177B1729D91E79572A8B7")

addappid(2677810)
addappid(3823920)