-- generated by KeySteam
-- update time: 2024-02-08
-- app_name: Hentai Senpai: Cosmic Beauties

addappid(2804250)

addappid(2804251,0,"456e07c812ece6ea70d89b720ecff9e2087a0f2d7090a8ce3b712efd24e28b07")

addappid(2806000)