-- generated by KeySteam
-- update time: 2025-12-12
-- app_name: 符文工厂3豪华版

addappid(2243710)

addappid(2243711,0,"48f545cab498f15092d267bd07ac909c46982c2730c2e878123db87dacbcd69c")
addappid(2243712,0,"898a15a42166018df5759186a084b737c6ec379b994cd3a454f9cbc0cae6ac5c")

addappid(2244790)
addappid(2244791)
addappid(2244792)
addappid(2244793)
addappid(2244794)
addappid(2244795)
addappid(2244796)