-- generated by KeySteam
-- update time: 2026-02-27
-- app_name: 奇幻拼图

addappid(2244880)

addappid(2244881,0,"b544215fb8edcb3cca2eb531674970d9e32352234b20c61b6c7c467da281d183")

addappid(2246690)
addappid(2246691)
addappid(2255340)
addappid(2281640)
addappid(2281641)
addappid(2285900)
addappid(2301840)
addappid(2301841)
addappid(2301842)
addappid(2894030)
addappid(2894040)
addappid(2894050)
addappid(2894060)