-- generated by KeySteam
-- update time: 2025-12-05
-- app_name: 无尽传奇 Remastered

addappid(2246670)

addappid(2246671,0,"e144ac4eb76015ab095c549730d07519d9ae2916c28c7f6940bfd7a0d8eb6b35")
addappid(2833370,0,"d5179861da87edc0542c6a0fe202ff8051045e81972da7091abb36632c215255")

addappid(3106360)
addappid(3106370)
addappid(3106380)
addappid(3106390)
addappid(3106400)
addappid(3106410)
addappid(3106420)
addappid(3106430)
addappid(3106440)
addappid(3106450)