-- generated by KeySteam
-- update time: 2023-03-23
-- app_name: No More Money

addappid(2246300,0,"055453ebb29ff3a8bd42005f21e0452920ee9acb4caa5f52cee45f8028b41e38")

addappid(2246301,0,"6e00c4062ad757ac2d9ed985d08a335494cd024c1cee3a53b71283ecf51134bb")

addappid(2247390)
addappid(2254960)
addappid(3126100)