-- generated by KeySteam
-- update time: 2025-07-29
-- app_name: Jury - Episode 1: Before the Trial

addappid(2258290)

addappid(2258291,0,"1a498a1ba9af0cd8e2465b653d7674c5b7030f799400a9f8927d91780c40be4f")

addappid(2874140)
addappid(3734730)