-- generated by KeySteam
-- update time: 2025-11-05
-- app_name: The Backrooms: Rescue Expedition

addappid(3267550)

addappid(3267551,0,"90d0fb98f797dcc980361f80a0a9ec9743efa1396eb9dfc875074475f2727ab6")
