-- generated by KeySteam
-- update time: 2026-03-15
-- app_name: 未完信䇳：纸鸢

addappid(3620740)

addappid(3620741,0,"b7654562959944aeb39faeafe91cbfdc26bfc969659d5362400c31d9311cf149")

addappid(3654070)
addappid(3654080)