-- generated by KeySteam
-- update time: 2021-07-27
-- app_name: Dream Daddy: A Dad Dating Simulator

addappid(654880)

addappid(654881,0,"8e82dbb1f4c7bb450e1448f093fc24c2efd707e2890b72d4207830ffbc270a13")
addappid(654884,0,"120a10ce54e14f457a369ee18c1ff5e0f98170b9c4c8553125708576480984ad")
addappid(654885,0,"0d93922f67a4e357d17bbc3113ce9d12dcaf9ff23453b608cf89b001819f068f")

addappid(930020)