-- generated by KeySteam
-- update time: 2018-01-29
-- app_name: Masked Forces 2: Mystic Demons

addappid(655000)

addappid(655001,0,"6f04eebb95bcaaeef0b16bb60e71db828cc2917e16e0f4809dda250343759a9f")

addappid(777120)