-- generated by KeySteam
-- update time: 2025-10-29
-- app_name: 星际卡车司机

addappid(2380050)

addappid(2380051,0,"a692f8ffe9b6df42b1c9344a8d1f0f92109fc67c1d094414b767b5e6a641d27a")

addappid(2873570)
addappid(3088950)
addappid(3218640)
addappid(3285520)
addappid(3933200)