-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: Luminous Skies: A Short Adventure

addappid(2384140)

addappid(2384141,0,"0d0afd32cc7496c084258c731bc467f20d82dad9006aed3aa3012e79b86de5b8")

addappid(2384220)
addappid(2384221)
addappid(2384222)
addappid(2840850)
addappid(2892120)