-- generated by KeySteam
-- update time: 2026-02-17
-- app_name: 真・三国无双 起源

addappid(2384580,0,"a48f892e064b01728580d88a2c13d6a003d87d467d7b5a16703684926b74965f")

addappid(2384581,0,"c9bfe8a78dc43f75438b3a8e602c7a322b0b53418f80be108058121a71371130")

addappid(3319840)
addappid(3319850)
addappid(3319860)
addappid(3319870)
addappid(3319880)
addappid(3319890)
addappid(3319900)
addappid(3319910)
addappid(3319920)
addappid(3319930)
addappid(3319940)
addappid(4038930)
addappid(4101630)