-- generated by KeySteam
-- update time: 2025-11-17
-- app_name: 奥特罗斯 Ultros

addappid(2386310)

addappid(2386311,0,"af749a581922a0c97f5cd9d034f04d877796b39acf48e7a430aae7f3dd52a852")

addappid(2649730)