-- generated by KeySteam
-- update time: 2026-03-24
-- app_name: STRAFTAT

addappid(2386720)

addappid(2386721,0,"d6706267b1aa5c534190b8bd47f12b11c89941f6b033bc216190d8cc6fe69aff")

addappid(3153370)
addappid(3868930)