-- generated by KeySteam
-- update time: 2023-05-26
-- app_name: 龙傲天的多元宇宙

addappid(2387780)

addappid(2387781,0,"8a59b4e05260845da74e37332d063111b2c2c799a62ec38e9619e5cfee6f3dd4")

addappid(2418190)
addappid(2418200)