-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: 方舟: 生存飞升

addappid(2399830)

addappid(2399831,0,"320e0bcc46f1e7d88e18488c73990878eedbc06c3284015e1d0af97abe143e23")

addappid(2827030)
addappid(2849450)
addappid(2881150)
addappid(2972680)
addappid(3059650)
addappid(3282470)
addappid(3349320)
addappid(3483400)
addappid(3571730)
addappid(3583650)
addappid(3675020)
addappid(3720100)
addappid(3720200)
addappid(3982300)
addappid(3982310)