-- generated by KeySteam
-- update time: 2021-06-29
-- app_name: 卡车人生

addappid(1066130)

addappid(1066132,0,"90f07c607592aa3b31b2e7bf53daa561245e251e758f5362398dc20e0a422849")

addappid(1130600)
addappid(1287490)
addappid(1385070)
addappid(1468080)