-- generated by KeySteam
-- update time: 2025-02-24
-- app_name: SKALD: Against the Black Priory

addappid(1069160)

addappid(1069161,0,"e74c024af3a1587e5fb2cfc293646bad96cd8af3525d45ac46cfc7320dffd267")

addappid(2902190)