-- generated by KeySteam
-- update time: 2025-10-27
-- app_name: Ultimate Admiral: Dreadnoughts

addappid(1069660)

addappid(1069661,0,"2ac313c2c0171e5f729d2433e47d343eba402d3d3440484e74b2731db0368126")

addappid(2672570)