-- generated by KeySteam
-- update time: 2022-07-11
-- app_name: 欺诈领主

addappid(1069690)

addappid(1069691,0,"b0b62c3ca8b5fdeae36530e7baa52e37ed21aee3ba813044d12e4458ff5c4240")

addappid(1556061)
addappid(1556062)