-- generated by KeySteam
-- update time: 2019-12-04
-- app_name: The Real Man Summer Championship 2019

addappid(1074310)

addappid(1074311,0,"7f1b58ab907b28cb3653dca1e505b7523968d4c5cc65f92de80a2619386e5177")
