-- generated by KeySteam
-- update time: 2022-04-05
-- app_name: 魔域之书

addappid(1076200)

addappid(1076201,0,"50ee1eeed9965f82ead8a6be6c534afef4ac5991a57be019e7c2f479e1442d14")

addappid(1518150)
addappid(1518151)
addappid(1518152)
addappid(1518153)
addappid(1704470)