-- generated by KeySteam
-- update time: 2019-05-14
-- app_name: Elemental Girls

addappid(1079310)

addappid(1079311,0,"e63607a594600f385dc1b69aced1ccdf2a1448d1923a5231c52c71f4d55ab2b2")

addappid(1079920)
addappid(1080710)