-- generated by KeySteam
-- update time: 2025-10-07
-- app_name: 昏迷 2B：地下墓穴

addappid(1781890)

addappid(1781891,0,"7695a89bfd4e0d3f27fb4028c30100e4cfda9fdd21241199a99b368961309df1")

addappid(3267780)
addappid(3267790)
addappid(3267800)
addappid(3267810)