-- generated by KeySteam
-- update time: 2022-08-31
-- app_name: Dusk Diver 2

addappid(1792600)

addappid(1792601,0,"8434d696dd21d12dca0589e96bffb42bee74bb26838a8dd9d7860c641ed76794")

addappid(1919820)
addappid(1930530)
addappid(1930660)