-- generated by KeySteam
-- update time: 2024-11-05
-- app_name: The hardest game in the universe 2

addappid(1792700)

addappid(1792701,0,"ebe8d7cde9295cd6547dce6756b32a57849cbaebbf9adb04eaf476304a8ba825")

addappid(2142830)
addappid(2827290)
addappid(2827320)
addappid(2827360)
addappid(2835840)