-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: Monster Train 2

addappid(2742830)

addappid(3580220,0,"6a48b119fa0f4779ec8618000d21337750db9a1e0eac4f89cdf1afb16ea4a7ec")

addappid(3993450)