-- generated by KeySteam
-- update time: 2025-10-07
-- app_name: 圣铠：地下城君主

addappid(2753600)

addappid(2753601,0,"c79707c0a6b3c96c9e1f39f9d6eeda3f26d55486e0db297d9e4d3f68cb0e577c")

addappid(3624980)
addappid(3624990)
addappid(3625000)