-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: Megaquarium

addappid(600480,0,"ecc6b41bdeb4e4750d99ed0a67bad0e6ee68e0bfa41f5a5eab9563dffc2d6692")

addappid(600481,0,"cfec171ac99a86936c242a0fa19e37eace19a84cd5d2adff51dfed55d536c887")

addappid(1315300)
addappid(1339440)
addappid(2574770)
addappid(4307900)