-- generated by KeySteam
-- update time: 2019-07-12
-- app_name: Spaceship Looter

addappid(600630)

addappid(600631,0,"479003e5b43102a8e82fd4743f9ae34569b67a707febbe40657fb4427e0f35b6")

addappid(675400)