-- generated by KeySteam
-- update time: 2022-08-17
-- app_name: Psychonauts 2

addappid(607080)

addappid(607081,0,"dfdca4a6e8f903ffd1a93290a893899e0726edc7a8c7b39fdff62b40c0994915")

addappid(3245600)