-- generated by KeySteam
-- update time: 2019-10-15
-- app_name: Blazing Chrome

addappid(609110)

addappid(609111,0,"a44222e81b30fa1a49201523cfd7dfc50c33ec5c94d02a7f48f75bce3e75e464")

addappid(1248160)