-- generated by KeySteam
-- update time: 2025-10-19
-- app_name: Love, Money, Rock'n'Roll

addappid(615530,0,"e985eb9384b9fc1ba324856319b5c8f65635b08cf34db2d87234f71efb13b259")

addappid(615531,0,"798a2870c2ddd7da29e898c6f9472b8b5dfcf9bb0799588e2ee149ba756da3f9")
addappid(615534,0,"c71f8ed70d1f2c2cc7d2b4a7d5268fbb350d874f5f4916911a0394ea1283714b")

addappid(2318010)
addappid(3313270)