-- generated by KeySteam
-- update time: 2025-09-29
-- app_name: 时光之塔

addappid(617480)

addappid(617481,0,"9679f72e357189f9e4df381c634dad5451f77202804263a2b10564605633502c")

addappid(713280)
addappid(3497290)