-- generated by KeySteam
-- update time: 2026-01-25
-- app_name: EGOS - Tales of Fallen Souls

addappid(619340)

addappid(619341,0,"9dac26c0e403d044f79fc24b2d6cc6a44aeb8cef4601361b4f7b2506e2cdbd53")
addappid(619342,0,"ace66c45d1bc040d28d7df5d433c22056f5c57400a48e26f43868ba57349c9c9")

addappid(746980)
addappid(854430)
addappid(1216900)