-- generated by KeySteam
-- update time: 2026-03-12
-- app_name: Wizardry: The Five Ordeals

addappid(1308700)

addappid(1308701,0,"8e2cd6a1a36611d2a178edb5ddef89704391742fef5c9384d80a4c93029fc61e")

addappid(1309770)
addappid(1309771)
addappid(1456541)
addappid(2889060)
addappid(4422250)