-- generated by KeySteam
-- update time: 2025-12-23
-- app_name: Space Battle

addappid(1309140)

addappid(1309141,0,"6683b03e9653b210e03708cde3cf6b0bfd180bc58bd580c6fcb2bb810df212e3")

addappid(2808620)