-- generated by KeySteam
-- update time: 2025-11-20
-- app_name: Achilles: Legends Untold

addappid(1314000)

addappid(1314001,0,"f8ea6ebbef185079adc617c41c6c867f04dcd43446d42aed3ca43a18a39ef4f8")

addappid(2445710)
addappid(2705610)