-- generated by KeySteam
-- update time: 2025-06-08
-- app_name: schoolLife 东洋中学之异闻录

addappid(2602050)

addappid(2602051,0,"b0e56f210ff1598bcb70839a4413e333841b88e56c649bf2100102a304b19c6b")

addappid(2636850)
addappid(3629900)