-- generated by KeySteam
-- update time: 2023-11-13
-- app_name: Foxy Tales

addappid(2609490)

addappid(2609491,0,"faaeeae7ebc51446d2fa3ecbbd62ddb299e21eef8eed49b6bce5efb19522e1ed")

addappid(2628630)