-- generated by KeySteam
-- update time: 2025-10-01
-- app_name: NUKITASHI 2

addappid(2614070)

addappid(2614071,0,"85b2e14de3f99250e09830257b8ce9b7344187e52cacf34930d5c218667b6b94")

addappid(3936700)