-- generated by KeySteam
-- update time: 
-- app_name: Agent A - 伪装游戏

addappid(801480)

addtoken(801480,"16059214099021938432")

addappid(801481,0,"1c5902efdfa3bee5b98733cac85ce9e1a73a5744e65a8623740c8d8c774dc4b6")
