-- generated by KeySteam
-- update time: 2021-04-07
-- app_name: FPV Freerider Recharged

addappid(813530)

addappid(813531,0,"8eebe27f588bcb9541f38dc067f78316ef3b1e9d2293be28000f1a22d0997017")

addappid(849540)