-- generated by KeySteam
-- update time: 2025-01-30
-- app_name: The Great War: Western Front™

addappid(2109370,0,"3a31bb00d422564610ef0ac06d6e72c49c6f5307b631d3ccd36a803ffb7004a7")

addappid(2109371,0,"10ef091d30c140edf4aaae9d81771407eb4c6053d7ed10c256f173c2661d5b6b")

addappid(2285590)
addappid(2285591)
addappid(2361670)