-- generated by KeySteam
-- update time: 2023-11-10
-- app_name: Forspoken

addappid(1680880)

addappid(1680881,0,"3a714f498834b6b17b15fd1864da4a1158074207edbc8e94912f7412adac8f70")
addappid(1680882,0,"36ab29f55972986cc4c4535ac7249791e305e217339ae47c65fb0816c1f53ab4")

addappid(1818430)
addappid(1818431)
addappid(1819220)
addappid(1819221)
addappid(1819222)
addappid(1819223)
addappid(1819224)
addappid(2279791)
addappid(2279792)
addappid(2279793)