-- generated by KeySteam
-- update time: 2022-06-12
-- app_name: 勇者一行与妖魔的考验

addappid(2056150)

addappid(2056151,0,"34943bc374ea9abeaa662cfe171b780782a7cf84b30423792196ce5859f59e5e")

addappid(2552890)