-- generated by KeySteam
-- update time: 2022-12-20
-- app_name: SOL CRESTA

addappid(1575640)

addappid(1575641,0,"5467b5331d7cd63ce66347f5401f150d665c39dd7e13b81072ea5fe2c15e8125")

addappid(1798120)
addappid(1802830)
addappid(1802831)
addappid(1802832)