-- generated by KeySteam
-- update time: 2021-12-10
-- app_name: The Shadow of Yidhra

addappid(1576240)

addappid(1576241,0,"06a2b637c0f40cc6cb8040d1d4ee9ed76a912defceb2871cf322f0c91c31893d")

addappid(1608380)