-- generated by KeySteam
-- update time: 2026-01-19
-- app_name: Prehistoric Kingdom

addappid(666150,0,"bdaa033c251a4a3e760e868fcb8c1c8642673bb42e5197b6572731f85e76eb81")

addappid(666151,0,"e4ed477c5cebc990e21bdc1f3f728043303a3c34a55b2a732e6652b28cbd689d")

addappid(2562770)