-- generated by KeySteam
-- update time: 2025-10-06
-- app_name: VTOL VR

addappid(667970,0,"6d5bb740323cbaf5e450db87b8c2595e1ded9a3e2b96f87dab6a32c635bbd512")

addappid(667971,0,"34da89de74099b39413bba485bc7fff7a4bebaad40a894b31bcbee4b3f207a0e")
addappid(1770480,0,"2274ce0ff2c9672e0c95404ea4df5f9ed22c295f00f6b9f017d3699c445e9425")

addappid(2141700)
addappid(2531290)