-- generated by KeySteam
-- update time: 2022-06-02
-- app_name: 8道门：雅兰的来世冒险

addappid(668550)

addappid(668551,0,"7ebdd4d951856d8b86c630d21d781b75c846bd487c6c1daa432e347b39a621f2")

addappid(1704110)