-- generated by KeySteam
-- update time: 2018-01-03
-- app_name: RC Plane 3

addappid(670500)

addappid(670501,0,"0f8f6be137105b8b4881990db96c8d634f85efd21da33b75447608ea85544dc9")

addappid(775880)
addappid(775881)