-- generated by KeySteam
-- update time: 2023-10-30
-- app_name: Boyfriend Dungeon

addappid(674930)

addappid(674931,0,"aeab3185ea4877938e9a4a9e2feb7d8950c41473c4110beeefc209e40db975b2")

addappid(1808990)