-- generated by KeySteam
-- update time: 2025-11-21
-- app_name: 泡泡龙：白糖地下迷宫

addappid(2937770)

addappid(2937771,0,"12b1a7d541f2f988f0f3b7aaf7de74fc43b2b82d0d270b87bd478cca3411eb66")

addappid(4142190)