-- generated by KeySteam
-- update time: 2019-10-25
-- app_name: Crystar

addappid(981750)

addappid(981751,0,"b5f84767c3819cf86493e80ae299514fd052a780441121db3eb8839e44d1784d")

addappid(1067471)
addappid(1067476)
addappid(1070050)
addappid(1070051)
addappid(1070052)
addappid(1070053)
addappid(1070054)
addappid(1070055)
addappid(1070056)
addappid(1070057)
addappid(1070058)
addappid(1070059)
addappid(1070120)
addappid(1070121)
addappid(1070122)
addappid(1070123)
addappid(1070130)
addappid(1070131)
addappid(1070132)
addappid(1070140)
addappid(1070141)
addappid(1070142)
addappid(1111350)
addappid(1111351)
addappid(1111352)
addappid(1128400)