-- generated by KeySteam
-- update time: 2025-09-15
-- app_name: 花语：百合

addappid(986280)

addappid(986281,0,"cc8c735bdc58a98e634e090d7eea50f3e07211f5857846031915fe411bb8feaf")

addappid(1058960)
addappid(1970490)