-- generated by KeySteam
-- update time: 2026-02-16
-- app_name: iVRy Driver for SteamVR

addappid(992490)

addappid(992491,0,"1a9d7637e8c9d0e2be9e5c3e66639ca1838a7bff8edcabb3c3208ecabd227a33")

addappid(1005970)
addappid(1005971)
addappid(1005972)
addappid(1021000)
addappid(1257790)
addappid(1487090)
addappid(1487091)
addappid(1501870)
addappid(1591080)
addappid(2261230)
addappid(2261231)
addappid(2772740)
addappid(2829580)
addappid(3260890)