-- generated by KeySteam
-- update time: 2019-05-19
-- app_name: Siluman Fantasy

addappid(997240)

addappid(997241,0,"b660b6658319359f0ed1617952aec5f3d678be86567373ad7418edf58cc9fcab")

addappid(997250)
addappid(997251)
addappid(997252)
addappid(997253)
addappid(997254)
addappid(1019380)
addappid(1056240)
addappid(1056241)
addappid(1056242)
addappid(1056243)