-- generated by KeySteam
-- update time: 2026-02-08
-- app_name: Futaland

addappid(4289400)

addappid(4289401,0,"c37809ff2c358307bad00939432f9cefd9e1ad0543afab5a3f608c5a78a39e48")

addappid(4333530)
addappid(4333540)