-- generated by KeySteam
-- update time: 2025-09-26
-- app_name: Broken Sword - Shadow of the Templars: Reforged

addappid(2544110)

addappid(2544111,0,"41ee7b846b2f1a26a8b38d4893ee96c2a435977fc4038f1c673035e14c64b66e")

addappid(3315730)
addappid(3361990)