-- generated by KeySteam
-- update time: 2026-03-24
-- app_name: Heróis de Noname

addappid(2427310)

addappid(2427311,0,"e20920a0a6f244bcac404051ba05cba7177e2170e0129ae355d10ba5fc211374")

addappid(2628840)
addappid(3124250)