-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: Sea of Thieves

addappid(1172620)

addappid(1172621,0,"d0a7c81c3c4ec69d5646531c500f6f8e46c7a42a74c6baf68a210c8db2f82117")

addappid(1453980)
addappid(1467220)
addappid(1594030)
addappid(1781320)
addappid(1928780)
addappid(2307680)
addappid(2309050)
addappid(2838640)
addappid(2838650)
addappid(2838670)
addappid(3444920)
addappid(3444930)
addappid(3937210)