-- generated by KeySteam
-- update time: 2025-09-26
-- app_name: Star Fetchers

addappid(1178030,0,"821d66f92fd1d71068e6fab5b45844500378eea8c060b0288c8e63f4d8ac61df")

addappid(1178031,0,"bdcb16b0b270b507d9380f58e881487decb980d28f679f58461c81e389c115eb")

addappid(1234570)
addappid(2869630)