-- generated by KeySteam
-- update time: 2023-11-07
-- app_name: 光明记忆：无限

addappid(1178830,0,"f065b725994bc8a5e5d08d1949d7b62e2d34de603a5b1bc736a961650b03b06f")

addappid(1554699,0,"bf04ebda1d1572665a129889cd9333e1f272a3fb37c2eb8cc58fe6dab1a08f7b")

addappid(1554690)
addappid(1780970)
addappid(1781000)
addappid(1781070)
addappid(1781100)
addappid(1870120)
addappid(1870121)
addappid(2218530)
addappid(2218531)