-- generated by KeySteam
-- update time: 2020-04-11
-- app_name: My Strange Girlfriends

addappid(1284800)

addappid(1284801,0,"412794385a807ba424e37b5f6c3b5b2a5d3c330fde832aa17ae857deb05e1f8b")

addappid(1290970)