-- generated by KeySteam
-- update time: 2023-12-19
-- app_name: No King No Kingdom

addappid(726000)

addappid(726001,0,"3bf0157ba38dcf5822c04e5d3f68dd27dadbf3dc3810810b466a61f4303721ca")
addappid(726002,0,"7149eae788135a4c961e6f3b29b346532584ae04b2f75e93c564f7d5391d11ad")

addappid(1679900)
addappid(1933250)
addappid(2078220)
addappid(2138370)