-- generated by KeySteam
-- update time: 
-- app_name: 中国式家长

addappid(736190)

addtoken(736190,"9153716071410537043")

addappid(736191,0,"cc96b6ac27f49e3e8e11b5e09bfeb0c7771b37e65e82d2056120641af6b74009")
