-- generated by KeySteam
-- update time: 2021-06-24
-- app_name: 9 Monkeys of Shaolin

addappid(739080)

addappid(739081,0,"aa1b588da2ee859a1e530435c7a206d0796edeea69790d1b8fc20f907b51b852")

addappid(1426920)
addappid(1426921)