-- generated by KeySteam
-- update time: 2026-03-18
-- app_name: Infinite Game Cartridge Collection

addappid(3942710)

addappid(3942711,0,"91F9A6BFF828145D56B7AA24EFD60E9D00143E1E2FC3E3522358A573455B73F9")
addappid(3964730,0,"4d45d4095c2c38a0b1bbd2443c5f966948a5cbd0442503fc597c6986e03b93a0")
