-- generated by KeySteam
-- update time: 2026-03-04
-- app_name: 东方魔女夜市

addappid(3950050)

addappid(3950051,0,"345f393c3d6cceb7c94f459fc73ae6e226fa739b98ff7050d821459a3da94c79")

addappid(4345670)
addappid(4383750)