-- generated by KeySteam
-- update time: 2021-08-05
-- app_name: Bloody Chronicles - New Cycle of Death

addappid(455310)

addappid(455311,0,"bd9e9847673eaca8193bfb89e6fc91c26f1900a1561372be7adc700ac95659b9")

addappid(999150)
addappid(1123700)
addappid(1123701)
addappid(1182540)