-- generated by KeySteam
-- update time: 2026-03-06
-- app_name: Crush Crush

addappid(459820)

addappid(459821,0,"aa604fcda9432e9771859c3e86da68938ee4ea9fe1ecef2756ecfa4b6a29e965")

addappid(948680)
addappid(3630990)
addappid(3950240)
addappid(4166260)