-- generated by KeySteam
-- update time: 
-- app_name: 《文字游戏》

addappid(1109570,0,"434a9c8a57340559362485355b2e52a7a957afca2ea5bc3599f15d2f8e9721d3")

addtoken(1109570,"16537240222139241145")

addappid(1109571,0,"80164c3cba3c8e54a398cc2797ce86e94fddc318ae615cd4a376be0fedfae9bc")
