-- generated by KeySteam
-- update time: 
-- app_name: The Almost Gone

addappid(1115780)

addtoken(1115780,"17028931102664223224")

addappid(1115781,0,"d48ece661d9803f46fca8078d34ce8f277c7b56f68054fade4905153e45e0dbd")
