-- generated by KeySteam
-- update time: 2019-12-04
-- app_name: Mineirinho Director's Cut

addappid(1201630,0,"1102df5cb916a463b82b9a556d556762b023764aafce180070f2fe2d40f5a732")

addappid(1201631,0,"c7f0efb35ccf55702c1c209fd2800a3b86ea34e2c216098270f61e4aaf0ea876")

addappid(1209600)
addappid(1424240)