-- generated by KeySteam
-- update time: 2026-03-06
-- app_name: 叛逆神魂 GODSOUL🔥

addappid(1213300,0,"877a197f18e3e4737a31eb713eb55d809723fb7a650efb5b3969f012a686bd19")

addappid(1213302,0,"a237589c759350160f6eaa4255cfbb51b778235d41e60ca9b6b5ce7936dcca04")

addappid(3573830)
addappid(3573840)
addappid(3573850)
addappid(3573860)
addappid(3573870)