-- generated by KeySteam
-- update time: 2020-06-05
-- app_name: Immortal Legacy: The Jade Cipher

addappid(1217220)

addappid(1217221,0,"9db147cda40ac1fe55c1ef1ec67da2a8a088f5f352342be66300c5229b236b2d")

addappid(1295240)