-- generated by KeySteam
-- update time: 2025-07-29
-- app_name: 波提：字节国度大冒险

addappid(2161050)

addappid(2161051,0,"f5aaffa0d070e7d43b932d3514f1a82b0f8eea99d4a82004c723cdd0fda67cc0")

addappid(2649360)
addappid(2729630)
addappid(2729700)
addappid(2736460)
addappid(2777280)
addappid(2777290)