-- generated by KeySteam
-- update time: 2026-02-07
-- app_name: Summer Crush

addappid(2163060)

addappid(2163061,0,"dfac7232179517a6bf02a2c313439355722499a0dbe842cba6098673dfa884b9")

addappid(2259480)