-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: Physics Lab

addappid(2167340)

addappid(2167342,0,"ca92c6e49c370cb5649efdea7ae9ceda09ba383f9de8740377e09d039a1ede35")

addappid(2660960)