-- generated by KeySteam
-- update time: 2025-08-03
-- app_name: 买个可乐饼吧！ - Buy a Croquette!

addappid(2167960)

addappid(2167961,0,"78200fa30dedb302ff83b7f427483b788bed995009b59303c2ca729d05d83309")

addappid(2616280)
addappid(2888970)