-- generated by KeySteam
-- update time: 2024-07-19
-- app_name: 剑侠．风尘恋曲

addappid(2179300)

addappid(2179301,0,"892591c64c3e69becc37b1771700c2a33bcf4adc3ffc6a89b99a8cedfec532b1")

addappid(2183310)
addappid(2401190)