-- generated by KeySteam
-- update time: 2018-09-06
-- app_name: 天岚行 - Through the Mist and Sky

addappid(865880)

addappid(865881,0,"412774409430e553e1f0a009d3bc3f0cd89d6ca61af1413edc9630dee31b9666")

addappid(865890)