-- generated by KeySteam
-- update time: 2023-10-23
-- app_name: Beat Stickman: Infinity Clones

addappid(866010)

addappid(866011,0,"b617758c1f71353f19463a7e5ab207818cede863b937bb9f052edcd5a38c97e4")

addappid(1152700)