-- generated by KeySteam
-- update time: 2025-05-26
-- app_name: 黑荆棘角斗场：重铸版

addappid(3168260)

addappid(3168261,0,"749bf7e07a235e19744c49d9e52c28077f3b903fa05cd3ca4f42f5dd1f949448")

addappid(3282660)
addappid(3363660)
addappid(3557410)