-- generated by KeySteam
-- update time: 2026-02-19
-- app_name: AppGameKit Studio

addappid(1024640)

addappid(1024641,0,"2cc293c4f5efc989dee5d5ef94a7a2ddc28500309f147c40d5ce44c984b1f4e3")

addappid(1033070)
addappid(1107700)
addappid(2123790)