-- generated by KeySteam
-- update time: 2025-12-03
-- app_name: Torque Drift

addappid(1029550)

addappid(1029551,0,"be8027e5929e7be5b64a639da0cc132be37d336da6b6b34796a25fe258a09e75")

addappid(1123432)
addappid(1123473)
addappid(1202600)
addappid(1326770)
addappid(1352720)
addappid(1352721)
addappid(1414130)
addappid(1414131)
addappid(1605970)
addappid(1605971)
addappid(1605972)
addappid(1641490)
addappid(1703940)
addappid(1989490)
addappid(2110420)
addappid(2192470)
addappid(2247140)
addappid(2445400)
addappid(3874820)