-- generated by KeySteam
-- update time: 2019-03-06
-- app_name: Nyasha

addappid(1035930)

addappid(1035931,0,"af91a1d150c8662d7f914a2197f814c040f7f08af25f50fcba0b9f95c68c6332")

addappid(1044260)
addappid(1080420)