-- generated by KeySteam
-- update time: 2025-09-30
-- app_name: Welcome to the Karoshi Club

addappid(2624950)

addappid(2624951,0,"4993df0928953d81665103febf10f03766c5b07345d9e5b49b148d3ad1762a60")

addappid(2722510)