-- generated by KeySteam
-- update time: 2024-10-04
-- app_name: Secret Pie (Adult Version)

addappid(1802870)

addappid(1802871,0,"ccad7ba97d05ac6585875c572974cf0ac57176ddc9f087e67cd77b2adb9d2af8")

addappid(2175960)
addappid(2461170)
addappid(2889150)