-- generated by KeySteam
-- update time: 2025-10-20
-- app_name: 《史力奇奇遇记：姆明山谷之歌》

addappid(1808680)

addappid(1808681,0,"157f66261c91bc328ad7ac3f9551dc063ee56f5f881679928732ec02f0e9e5ba")
addappid(1808683,0,"957d4d27e12060d0c29f5cfddb63d8d5653ef2180c3711d5ca385eb7c7e8bca0")

addappid(2782680)
addappid(2782690)
addappid(2875880)