-- generated by KeySteam
-- update time: 2026-02-27
-- app_name: Renryuu: Ascension

addappid(1809530)

addappid(1809531,0,"c9ece1f7b875917d59c400789aa63d0e1eb1fe393357ad528bb1ddc403fab651")

addappid(1865200)