-- generated by KeySteam
-- update time: 2023-12-14
-- app_name: Summum Aeterna

addappid(1815230)

addappid(1815231,0,"755ca7a9adff76b7b15f42029d5cf61e6ae8b54dcb0e331a2094fee67b6adce8")

addappid(2562920)