-- generated by KeySteam
-- update time: 2024-02-22
-- app_name: Goat's Tale

addappid(1702180)

addappid(1702181,0,"b28c87395fd7fd381ce09deaa4835e455560c8923fa81d15c485ed014794139b")

addappid(1847090)