-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: Drug Dealer Simulator 2

addappid(1708850)

addappid(1708851,0,"9da58ce930b5409698dfdd9945f19efdbe1e0b7acead98d61080b5b7058f9890")

addappid(3064210)
addappid(3169480)
addappid(3385220)