-- generated by KeySteam
-- update time: 2024-04-07
-- app_name: 东方冰之勇者记：序章

addappid(1715460)

addappid(1715461,0,"9172f102a4d9872bbae894d716853446987cbc0ae9ace89df04e58caf0fade92")

addappid(1852710)