-- generated by KeySteam
-- update time: 2023-07-20
-- app_name: Mahokenshi - The Samurai Deckbuilder

addappid(1717640,0,"a6487ae95e841f1103bb6974992cc2e548e9129a8268ef63d9ff0fee79811ff2")

addappid(1717641,0,"89cf1c23a2f11645996a33ab2b8793a6d64b017d44f9c587d0c746488500bf12")

addappid(2399250)