-- generated by KeySteam
-- update time: 2024-06-21
-- app_name: AI Solitaire

addappid(2301670)

addappid(2301672,0,"011894d5d86fe24c00f80fa76f40ab7cda7a5b1e00be4622cd04775b468cebb0")

addappid(2308270)
addappid(2308271)
addappid(2308272)
addappid(2308273)
addappid(2308274)
addappid(2963380)
addappid(2963400)
addappid(2963420)
addappid(3066730)
addappid(3066740)
addappid(3066750)
addappid(3066760)
addappid(3066770)
addappid(3066820)
addappid(3178050)
addappid(3178070)
addappid(3458440)
addappid(3458450)
addappid(3799700)