-- generated by KeySteam
-- update time: 2023-05-05
-- app_name: 觅光：第一章 - Seeking Light : Chapter 1

addappid(2305480)

addappid(2305481,0,"923c6ec21301f270123f092a0d9236aebfee12d4ae9209b68e8b325b61d1101d")

addappid(2365930)