-- generated by KeySteam
-- update time: 2025-09-13
-- app_name: 兵团突击：现代战争

addappid(2310160)

addappid(2310161,0,"d9e66eb033b40fd60533dc60970313ca9fa354a0c6edcb559cffea6b9094d0ed")

addappid(3124490)
addappid(3216920)
addappid(3280600)
addappid(3280610)