-- generated by KeySteam
-- update time: 2021-04-11
-- app_name: Tower of Waifus

addappid(1502230)

addappid(1502231,0,"d61b15ab225cc1fa8ada555dc3048f5446eb4ada26dfabbc01a04b19aafbaaf0")

addappid(1536050)