-- generated by KeySteam
-- update time: 2021-10-03
-- app_name: 爱与战争：天选将军

addappid(1508680)

addappid(1508681,0,"49f5ff76cf50a3adbbf14e284efcf8faf6bb9b3af96c8e91ffa3a8650dd8d05d")

addappid(1599180)
addappid(1660900)