-- generated by KeySteam
-- update time: 2025-10-05
-- app_name: Escalation!

addappid(1513420)

addappid(1513421,0,"14302e0f2a2d055348ca238241f0da8be063775c8adbf1dde72f55d09b06bb09")

addappid(1805530)