-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: COGEN: 大凤羽空与刻之剑

addappid(1514380,0,"45148079ccf0eb50668ec577afd1d172c5614483af9d64f4c7de504c94b107fd")

addappid(1514381,0,"d85f9fc72eb520ce836a9079038c1550003690a1c05a6086056912574f2820fd")

addappid(1644060)
addappid(1644061)
addappid(1644070)