-- generated by KeySteam
-- update time: 2022-02-18
-- app_name: Beans: The Coffee Shop Simulator

addappid(549240)

addappid(549241,0,"f8954c35da9c5b9f627e325ca31f24621e85adcf0eabce2f9d586a0fe393f058")

addappid(648080)