-- generated by KeySteam
-- update time: 2025-09-05
-- app_name: Realpolitiks

addappid(553260)

addappid(553261,0,"a75176bcaffd099f5d40bec29cf915ecb2f4061b0aeafc71af5679690ecc6161")

addappid(622360)