-- generated by KeySteam
-- update time: 2020-05-06
-- app_name: Monster Energy Supercross - The Official Videogame 3

addappid(1089830)

addappid(1089831,0,"bcc54a019d621b0246fba54e163d0830a7be2e8b38ece6ceccbe96984883b745")
