-- generated by KeySteam
-- update time: 2025-10-15
-- app_name: Vampire: The Masquerade - Coteries of New York

addappid(1096410)

addappid(1096411,0,"4ab6540a3c86f58819c7d643d1fbd362a400be3fcc51e006a4b6d325399250fe")

addappid(1266750)