-- generated by KeySteam
-- update time: 2025-10-15
-- app_name: Vital Signs: Emergency Department

addappid(1096640)

addappid(1096641,0,"b831b42b111f4745fd6c847b7b4b0447bb433be79ffcd2b19ea84f2deb3e381b")

addappid(1161560)
addappid(1161561)
addappid(1201820)
addappid(1201821)