-- generated by KeySteam
-- update time: 2023-07-25
-- app_name: 花园魔三国

addappid(1240480)

addappid(1240481,0,"7ee5bd3403b216e856fdda34cd8f7dce9e586638a2bb5515f396ae07bf2b5cc0")

addappid(1936880)
addappid(1997730)