-- generated by KeySteam
-- update time: 2020-02-18
-- app_name: Teacher Lady

addappid(1245090)

addappid(1245091,0,"d045e2b306a1921fc2eb1e294d85a814bff742a5802affc4511db8367190a077")

addappid(1245340)