-- generated by KeySteam
-- update time: 2020-05-09
-- app_name: To the Edge of the Sky

addappid(1247460)

addappid(1247461,0,"1a2a0b5226ae98186af290255d7319e6413e4643a1563fc6080774644b37f67d")

addappid(1282680)
addappid(1282681)