-- generated by KeySteam
-- update time: 2022-08-22
-- app_name: 琳 ， 画在方块上的少女故事

addappid(1249080)

addappid(1249081,0,"00507ec8d1e33f96b687161a87713065ebe5e6bc0dea4ac9cc492a29ebbc6bdb")

addappid(1392270)
addappid(1392271)