-- generated by KeySteam
-- update time: 
-- app_name: 忍者龟：施莱德的复仇

addappid(1361510)

addtoken(1361510,"2764735786934684318")

addappid(1361511,0,"5954562e7f5260400040a818bc29b60b335bb690066ff767e20d145a3b6b4af0")
addappid(2348930,0,"cd65db36fbcdc7c86ada27a6e96064807a6576a135f2ac7a4cb204d11173ca26")
