-- generated by KeySteam
-- update time: 2025-12-12
-- app_name: Animaze

addappid(1364390,0,"776c6a680c50dc530274a1a4699bc4b7fbd8a49b091bd40076c41d34548835ff")

addappid(1364391,0,"a99c58b77a65255cf19c64ca6f1459503c94e53f93331e552830e4b9bc0e11d6")

addappid(1430880)
addappid(1430881)
addappid(3325930)
addappid(3325940)