-- generated by KeySteam
-- update time: 2023-05-19
-- app_name: 袋鼠闯天关

addappid(1370140)

addappid(1370141,0,"3f8629fbb74ca939c630c00762b9622a3a5e17611b0a9e65db4caebdb2dbec12")

addappid(2052960)
addappid(2052961)
addappid(2052962)
addappid(2052963)
addappid(2155050)
addappid(2249670)
addappid(2389070)