-- generated by KeySteam
-- update time: 2025-11-02
-- app_name: Age of Fear 2: The Chaos Lord GOLD

addappid(341150)

addappid(341151,0,"024d02dbda756f5a20093d4f499443453be67b77b823c45a9fb7b7164aba4453")

addappid(577110)