-- generated by KeySteam
-- update time: 2025-11-25
-- app_name: Hatred

addappid(341940,0,"f2787cfe81aa233bef74cda9beeba8da1c3500c404c3332eff7bffbc5bf2cd50")

addappid(341941,0,"9a058f86501451492d08c6eb37d6bd51e6937951ac04de40caa6c7feea376fc9")
addappid(341943,0,"EC9A9BEA448E7BD6FD92DA86E97FFB5357B9222A0EE71D35B37D92655E011CE3")

addappid(1171890)
addappid(1580880)