-- generated by KeySteam
-- update time: 2026-02-18
-- app_name: TyranoBuilder Visual Novel Studio

addappid(345370)

addappid(345371,0,"ec67d7097f3cbd7b2b2fbfcbaadd805fb26f28f043eed4203619ca5773dd824d")
addappid(345373,0,"c4f9df83aa8475583cb43158b1affd24494481c9f54602f98e6ec1e6c56817a8")

addappid(2104500)
addappid(2120780)
addappid(2206370)
addappid(2408850)
addappid(2408851)
addappid(2410380)
addappid(2597720)
addappid(2597730)