-- generated by KeySteam
-- update time: 2026-03-04
-- app_name: 后宫绮梦 Harem Fantasy

addappid(3886870)

addappid(3886871,0,"c6b3980edea75863215d46482708da35cf935d055507441fbe951db4df4dfafb")

addappid(4100560)
addappid(4100570)
addappid(4100580)
addappid(4449130)