-- generated by KeySteam
-- update time: 2026-03-26
-- app_name: 星砂岛

addappid(2966320)

addappid(2966321,0,"ce86c628c5c525587d2aea36d5a745c980584e22eca6389d8bfd7a63c0db1c4c")

addappid(4391920)
addappid(4395490)
addappid(4424260)
addappid(4460980)