-- generated by KeySteam
-- update time: 2025-09-09
-- app_name: 这个CEO我当定了！

addappid(3570340)

addappid(3570341,0,"0daeb13752d79b61c8619efee594bea3e4b923cdba0c490e0e0e91f5a005874e")

addappid(4039780)