-- generated by KeySteam
-- update time: 2022-11-02
-- app_name: When The Night Comes

addappid(1400870)

addappid(1400871,0,"393d9be2ef2b87dbc51010a22c5bd995adc2eafbbd77b6e6b6af5cc351619e92")

addappid(2173950)