-- generated by KeySteam
-- update time: 2022-10-29
-- app_name: 脆弱的心

addappid(1412890)

addappid(1412891,0,"dcd7c24e04ec5373cfd53ab8952749427874fabe80e174bdaaa24be74e39b436")

addappid(1714160)
addappid(1714161)
addappid(2103560)