-- generated by KeySteam
-- update time: 2026-02-10
-- app_name: 红色的炼金术士和白色的守护者 ～蕾斯莱莉娅娜的炼金工房～

addappid(3259600)

addappid(3259601,0,"ae634a9eec6e2ae45901364376e5c088e269ae26071c8b7741b4a9b681bdf85c")

addappid(3811080)
addappid(3811090)
addappid(3811100)
addappid(3811110)
addappid(3811120)
addappid(3811130)
addappid(3811140)
addappid(3811150)
addappid(3811160)
addappid(3811170)
addappid(3811180)
addappid(3811190)
addappid(3811200)