-- generated by KeySteam
-- update time: 2025-10-08
-- app_name: 超级忍 反攻的斩击

addappid(2361770)

addappid(2361771,0,"6077dc2b1a88a7ae7a34470113e609a77bfc721374f4b17e20abc2f975ad2d85")

addappid(3381210)
addappid(3381220)
addappid(3381230)
addappid(3381250)
addappid(3381260)