-- generated by KeySteam
-- update time: 2026-02-09
-- app_name: Demonheart: The Cursed Trial

addappid(2364560)

addappid(2364561,0,"e3c8c5a0f076b7361316a29907df470f1211978d1a732903121f648faa08ce73")

addappid(2722250)
addappid(3699290)