-- generated by KeySteam
-- update time: 2025-02-28
-- app_name: An Arcade Full of Cats

addappid(2368470,0,"58559fd1b5031102a9d813204a4c8b808371fc8b65d35e0ba80e8d6a59b35d54")

addappid(2368471,0,"7b10f3b7ec0e6263e676eb1c225ef4b8d9296feccc292586a6f5b71e8f8720a4")

addappid(2582360)