-- generated by KeySteam
-- update time: 
-- app_name: 谍：惊蛰

addappid(2374000,0,"6ad9eb2b3d2e125b75b860da33dadc5dcb8d82809b801585fd7b7f4211b850a1")

addtoken(2374000,"6201546420746700519")

addappid(2374001,0,"cdbe149547ceb64384de08a06d926c7f059565e7d85de3a181073bd7ece0b9b3")
