-- generated by KeySteam
-- update time: 2025-05-02
-- app_name: The Coffin of Andy and Leyley

addappid(2378900)

addappid(2378901,0,"7e8df27c22fc52c5f740357a93710dcdb613817ef5c9e61763f20eb28b73d525")
