-- generated by KeySteam
-- update time: 2023-01-31
-- app_name: ToS Gamepad Companion

addappid(1841350)

addappid(1841351,0,"74fe993adad65f898da48029cb9bfa19ecd609612fae1bfd54fce2b76be94915")

addappid(1848060)
addappid(2217130)