-- generated by KeySteam
-- update time: 2025-08-19
-- app_name: 阿瑞亚之旅

addappid(1866980)

addappid(1866981,0,"d0a56afaad1bad91e9f936e956c66c7a3a100a94cbcd509efc35a35e13856411")

addappid(2961620)
addappid(3325450)