-- generated by KeySteam
-- update time: 2023-06-30
-- app_name: Candle Knight

addappid(1879680)

addappid(1879681,0,"9cb6a9082de4bdfdfe9e6872827ef9e5bccf28fee8038a03f841b7bc0f9f5fcd")

addappid(2435580)