-- generated by KeySteam
-- update time: 2025-06-02
-- app_name: Wedding Witch

addappid(2529820)

addappid(2529821,0,"f6da43b73303ced9a9784ea87fdd5b4765cf4d6aec263bfc71b745fcbb123ca1")

addappid(2638000)