-- generated by KeySteam
-- update time: 2025-05-08
-- app_name: 暗影帷幕：《五轮传奇》

addappid(2536960)

addappid(2536961,0,"3df080decc628928621080b03652e6b736eb4d35e609da5e4d94a2c8877c5457")

addappid(3555070)
addappid(3555080)