-- generated by KeySteam
-- update time: 2025-12-07
-- app_name: Noblesse Oblige: Legacy of the Sorcerer Kings

addappid(2537730)

addappid(2537731,0,"480297cef472f66d2a1db7988636e3f050f1de29171607b2317b8af111d484ca")

addappid(2543260)