-- generated by KeySteam
-- update time: 2020-10-29
-- app_name: Sense - 不祥的预感: A Cyberpunk Ghost Story

addappid(1120560)

addappid(1120561,0,"3f2d21a1974e80d2fb0860a684ad101e3fd33ba38b5c977f77f6476285bd47b1")
addappid(1120562,0,"5a342a71180a67c4336957d8edf8414856a3029db5d1962fbc7819f000d439e2")

addappid(1547810)