-- generated by KeySteam
-- update time: 2026-03-05
-- app_name: Planet of Lana II

addappid(2997230)

addappid(2997231,0,"a397e3852d84a423e6087d18c06db8f5a9123a2b20acee6f925c214b021dfd2d")

addappid(4349060)