-- generated by KeySteam
-- update time: 2023-02-09
-- app_name: 生化奇兵：无限 完全版

addappid(8870)

addappid(8878,0,"0b51342da3c2d54a398c08a62b3f31c391ad027a485c78a859d8224258a77709")
addappid(224091,0,"b94a9cbd1e44ebe744d960186af1678123ba134a8cc08fd8e5020ca153416011")
addappid(1523211,0,"6111b2e3d21efa5e5b26a91f75ff32d12aa8c5bb547c4d0215eda184a7f4c49b")

addappid(214930)
addappid(214931)
addappid(214932)
addappid(214933)
addappid(214934)
addappid(214935)
addappid(214936)
addappid(214937)
addappid(220140)
addappid(220159)
addappid(243411)
addappid(243412)
addappid(243413)
addappid(243414)
addappid(243415)
addappid(2028850)