-- generated by KeySteam
-- update time: 2025-10-10
-- app_name: Cuisineer 猫娘小厨

addappid(1963570)

addappid(1963571,0,"18dae24b737b1b3b430cd23b33b0ce4058f0b6ba568710aa5a64ecb1d3177b68")

addappid(2591650)