-- generated by KeySteam
-- update time: 2024-04-24
-- app_name: Do Not Feed the Monkeys 2099

addappid(1964040)

addappid(1964041,0,"ad5778a8902bb322ef67069868979cff5e4b97f00025fa24cd2db4e25fece9a8")

addappid(2525970)
addappid(2555210)