-- generated by KeySteam
-- update time: 2022-10-20
-- app_name: 键盘侠干他喵的多元宇宙

addappid(1721170)

addappid(1721171,0,"2384f8deb443147284cb2d0093e12e3e6c89571ccc48e47057346e9c10588d8d")

addappid(1890070)
addappid(1946130)
addappid(1946131)