-- generated by KeySteam
-- update time: 2023-10-04
-- app_name: Sudocats

addappid(1725640,0,"0fb30a6346ecc97829216f61a6f6fcb075eac6082ada62ee9d95dce56d65f5e3")

addappid(1725642,0,"537ac520a4697350d930ee58abe69f32b0c9e28410b174847399d663ec3309fb")

addappid(1923540)