-- generated by KeySteam
-- update time: 2024-09-27
-- app_name: Bulanci

addappid(1732920)

addappid(1732921,0,"34f187241217260273ebc2a4bc3f681001c5c60ab91c63eba6e1a40ad25748e0")

addappid(2400030)
addappid(2553060)
addappid(2553070)
addappid(3097980)
addappid(4167270)