-- generated by KeySteam
-- update time: 2024-05-07
-- app_name: Phantom Fury

addappid(1733240)

addappid(1733241,0,"3cfe77c0a8458712950b1f1eb9485e8846e4b1aa4410171c47bdc02eb0c03096")

addappid(2934670)