-- generated by KeySteam
-- update time: 2025-10-07
-- app_name: Scarlet Hood and the Wicked Wood

addappid(1141120)

addappid(1141122,0,"6403f4bccd615b628a25a15a30e20f4b484a1d483b48ab3d6d2005ba5b73487b")

addappid(1566750)