-- generated by KeySteam
-- update time: 2019-10-18
-- app_name: Mahjong Dimensions 3D - Fantasy Anime

addappid(1153220)

addappid(1153221,0,"ba429a79eaad806d6b77a8860a0d4bdacc7370a52d0d1b427d690ac3fc30bacd")
