-- generated by KeySteam
-- update time: 2025-05-21
-- app_name: 佐瑞亚：碎裂纪元

addappid(1159090)

addappid(1159091,0,"ca1a220351cdfbfc159915fb62baa7c1d066b84049dc8e9e6e91786c8a94a7bf")

addappid(2726430)
addappid(2769850)
addappid(2769860)
addappid(2853200)
addappid(3217410)
addappid(3240690)