-- generated by KeySteam
-- update time: 2019-04-30
-- app_name: Agony

addappid(487720)

addappid(487721,0,"0967d8650f46351598c6be9dded65dedf0b957a5ec0644e5ebd4378d76fb1c17")

addappid(1028120)
addappid(1921050)