-- generated by KeySteam
-- update time: 2018-12-12
-- app_name: 第九日-The 9th Day-

addappid(491420)

addappid(491421,0,"90ec7dc750ea6bd728ad11626fe8ee4eee4ff262beee4134d1630839271e1a80")
addappid(491422,0,"4c7e2a2cd06751e7bb12faaa9707f214cc9cb7bf5c1fc3dfdab48fddd3cc7631")

addappid(593990)
addappid(989480)
addappid(989500)
addappid(991580)