-- generated by KeySteam
-- update time: 2026-02-27
-- app_name: 银河旅店

addappid(2183670)

addappid(2183671,0,"ceefb359e132c750d33edaef6cfd205fffdea95d608acab6ace313a8025e01d7")

addappid(3860260)
addappid(3860270)