-- generated by KeySteam
-- update time: 2025-07-20
-- app_name: Poozle Mania

addappid(2191080)

addappid(2191081,0,"ed77408141afea2662d2341e87a32f30f84f1cec1dc975bf7a85ea43802317c7")

addappid(2441410)
addappid(2693970)
addappid(2978660)