-- generated by KeySteam
-- update time: 2026-03-18
-- app_name: 寂静之歌

addappid(2195410)

addappid(2195411,0,"9634043c605d62441a08ab388b7013a6cedb82be1cff7dbcdf8a8f77045a773a")

addappid(2685660)
addappid(3400120)
addappid(3560460)
addappid(3670070)
addappid(3676040)
addappid(3774820)
addappid(3776820)
addappid(4179260)