-- generated by KeySteam
-- update time: 2026-03-18
-- app_name: Mars Attracts - 火星人闹翻地球

addappid(2760580)

addappid(2760581,0,"db681438192b6f3d7ea13050140a1056a1dcf7f9b9883ea46536f94420f9d474")

addappid(3888510)
addappid(3959660)