-- generated by KeySteam
-- update time: 2026-01-15
-- app_name: 诸天刷宝录

addappid(2776450)

addappid(2776451,0,"d344b9a8eb3356663a0ad386889d0a675acdf4e1b2e41aa43d220e0ef38e65a8")
addappid(2776452,0,"5dfd6d9811882cd6da7723ad0578e41691fde46e771cf807bc1c88eb807aa733")

addappid(3396410)
addappid(3899280)
addappid(4241290)