-- generated by KeySteam
-- update time: 2025-10-08
-- app_name: Fatrifice

addappid(2340250)

addappid(2340252,0,"4a00192e8870ad0440106ffa1fdd28f7e380ceceac07cd562e8ee3f9d820a544")

addappid(2345420)