-- generated by KeySteam
-- update time: 2025-07-18
-- app_name: Legend of Cina

addappid(1041390)

addappid(1041391,0,"1d6896e6291aedb716c0d962a3ee3b4f1b66e8d74eb2e9780ae2a0ed2736498e")

addappid(1086330)
addappid(2301660)