-- generated by KeySteam
-- update time: 2025-11-29
-- app_name: 酿造物语 (Hundred Days - Winemaking Simulator)

addappid(1042380,0,"de193e280762c13ad0427214c360740cabd058a5ab348c8081656b171db05c4a")

addappid(1042381,0,"6674f981af8da7936c143330fd466489ce26f95b2be45b5598f8413c2e6a7285")

addappid(1681050)
addappid(1780830)