-- generated by KeySteam
-- update time: 2024-07-29
-- app_name: Lantern of Worlds - Storybook

addappid(1047190)

addappid(1047191,0,"3c6f18961c91bda468e5bf867c06b5a1accd7ab2067229bc3483b30a5b43c17c")
addappid(2812410,0,"57baaae02a53ad0ba7290f00aaf477f86bbd6170f4098b6b868405adb239bfbd")

addappid(2999470)