-- generated by KeySteam
-- update time: 2021-08-02
-- app_name: Minute of Islands

addappid(1049710,0,"573a89987ba1ae3d605283ec0a843c7a6b9988b5ca5b8876ebfb48e5584b1066")

addappid(1049711,0,"42c91fb9dab9deaab514c2c31c960b8fbdb8ce3d359029015864eda747a96bd5")

addappid(1535390)