-- generated by KeySteam
-- update time: 2019-08-29
-- app_name: Bear With Me: The Lost Robots

addappid(1050000)

addappid(1050001,0,"f1f91d494048f52600bb4e04a6ead50857d39b888ffd72276e0175af53854735")

addappid(1056770)