-- generated by KeySteam
-- update time: 2026-02-03
-- app_name: Pixel Puzzles Traditional Jigsaw Puzzles

addappid(1058200,0,"ef4a667f75411c83ba0a34cbb3a7cb19cfb1f28c7ff2ce2b1a91c98bf8232b93")

addappid(1058201,0,"18230c32b07ed02e72d48a40f6e853eb14e94665368e9aa6a7b933784b847962")
addappid(1176206,0,"7a5bebddc414c8ed4b9b39fecabd8f86c21f505a59bbcb3c1d85fd2c5804e445")
