-- generated by KeySteam
-- update time: 2026-01-15
-- app_name: Driver Booster for Steam

addappid(920490)

addappid(920491,0,"c6800cbcdb088aee9ea0481c759bacc9677de929ceb9752df329cfe9460b32d3")

addappid(920630)