-- generated by KeySteam
-- update time: 2021-11-05
-- app_name: 阿比斯的宝藏 - Treasure of abyss

addappid(932570)

addappid(932571,0,"0293f8e1c6d72b534903b2765a722c971b2077b5414d0a585ba500847f63de49")

addappid(1008540)