-- generated by KeySteam
-- update time: 2019-07-10
-- app_name: Hell Wedding 夜嫁

addappid(934580)

addappid(934581,0,"b08601d3dee6f34661b9d6dab17772492d5341d56f231244445afd19336f2feb")

addappid(1073180)