-- generated by KeySteam
-- update time: 2025-11-06
-- app_name: True Fear: Forsaken Souls Part 2

addappid(935580)

addappid(935581,0,"5189384649509bf26954427f07053444bf283a875495d79dfd4897d265b3ed26")
