-- generated by KeySteam
-- update time: 2026-03-16
-- app_name: Getting Inside: Hentai Story

addappid(3478920,0,"661dadee6c3cb071e6b25886f198b3a2329c6eb82a2f2b8040c792c1a1ac1df7")

addappid(3478921,0,"d1bd2d72bc41298aea4d612ff01e64d20bb9a7cf4ac4b9134d0c6ce2fad638bf")

addappid(3823390)
addappid(3823400)
addappid(3823410)
addappid(4329220)