-- generated by KeySteam
-- update time: 2026-02-02
-- app_name: 七界：拉菲恩圣地

addappid(2580130,0,"89e2e6e4184abf2dea0e33341eac747daf416e0eb292b3b4a7298b6afafedf85")

addappid(2580132,0,"5a73798d8903015918ca9170611938e57b16e955176c82c1abc7706d58496890")

addappid(3277900)
addappid(3277910)