-- generated by KeySteam
-- update time: 2025-12-22
-- app_name: 我的可爱女儿 / My Lovely Daughter

addappid(580170)

addappid(580171,0,"941dffc83c78c5187b363a41ccdd15d251258a6525e7ff068b90a024a428f953")

addappid(1033040)
addappid(2505420)
addappid(2998360)