-- generated by KeySteam
-- update time: 2025-06-21
-- app_name: Super Army of Tentacles 3: The Search for Army of Tentacles 2

addappid(592200)

addappid(592201,0,"5d6a8c2b1a8e8bd22140ffdc45f3a6b1e06a3005b7ff3fa17eaa479dea97bc2f")
