-- generated by KeySteam
-- update time: 2022-06-21
-- app_name: Furi

addappid(423230)

addappid(423231,0,"156dd9e4eb8c7891a53e579ff33bf7aac55c26b1d5de6153aa1fe3688d04fffd")

addappid(567810)
addappid(1802170)
addappid(3612090)