-- generated by KeySteam
-- update time: 2018-09-14
-- app_name: 地城进击者

addappid(429620,0,"49f4f75f32e68171b0f31be84d135e27e334f5757f5a1cbdd462c2ff2e6552c5")

addappid(429621,0,"35d8e8fe56ef15284d32543fe6d810c0dd2188bccfd596d606a90ffd2218a1d9")

addappid(577630)
addappid(581950)
addappid(581951)
addappid(582230)
addappid(804980)