-- generated by KeySteam
-- update time: 2020-06-06
-- app_name: Hidden Folks

addappid(435400)

addappid(435402,0,"fed12eb73cc580086d1a70c6408b0e174084178584e9c751adead9abc5a49f14")

addappid(811460)
addappid(891820)