-- generated by KeySteam
-- update time: 2018-12-14
-- app_name: Nya Nya Nya Girls (ʻʻʻ)_(=^･ω･^=)_(ʻʻʻ)

addappid(963330)

addappid(963331,0,"1ec456d2b2ea38bf43172e6b6d65af62aeb687266322ffc1df8482d9069984ec")

addappid(997470)
addappid(1082040)