-- generated by KeySteam
-- update time: 2025-12-11
-- app_name: 沉睡的法则 Things as They Are

addappid(965820)

addappid(965821,0,"2b4ee1a93aaacb175738e8c12d97bac8b3067f97136ef17026e45150cc5220db")

addappid(1121740)