-- generated by KeySteam
-- update time: 2020-06-19
-- app_name: 西游记之大圣归来

addappid(967240)

addappid(967241,0,"2202eb5ce917d02aebfc672e071df05ef84f56435460eda8794b8232681f43c5")

addappid(1177280)
addappid(1179330)