-- generated by KeySteam
-- update time: 2019-02-04
-- app_name: バインドを解除する(unbind)

addappid(977590)

addappid(977591,0,"886df2bb52466ff51608ecf9c2101f853b83232964026fe41569be7dae59afd7")

addappid(993410)
addappid(3305850)