-- generated by KeySteam
-- update time: 2025-09-02
-- app_name: Kokoro Clover Season1

addappid(1822230)

addappid(1822231,0,"5E96D7669D994AD2CA8A7C47D20CA2FE8C3839123448576A3FBB5A8DFEE3F16D")

addappid(2235080)