-- generated by KeySteam
-- update time: 2024-01-26
-- app_name: Inheritance: Ladeina's Path

addappid(2204040)

addappid(2204041,0,"ee439f95b877449b8a024d1f210a132b4bd4c18a6e3d0fa538907786692c7bf3")

addappid(2212240)
addappid(2395090)