-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: Scourge Of War - Remastered

addappid(2205330,0,"6b562f37bd1d06ebcbb6d57f9e659578a0907f9221dc6968cd98cf56ca6a7cbc")

addappid(2205332,0,"53b677bd1c09ce8b076074bd7cb31e530faf10940692714aa754df801443ca69")

addappid(3136610)
addappid(3136660)
addappid(3136670)
addappid(3136680)