-- generated by KeySteam
-- update time: 2026-03-23
-- app_name: 白键上的协奏曲：卡宏往事

addappid(3693720)

addappid(3693721,0,"6adda05d1aa955936a8f0b5cd67219d6dd98ea602fb8816a7fee9def6a5147f0")

addappid(4001970)
addappid(4270720)
addappid(4270730)
addappid(4499050)
addappid(4499060)