-- generated by KeySteam
-- update time: 2025-10-29
-- app_name: 末日准备狂

addappid(761830)

addappid(761831,0,"46eeb5fdced56fe223ab7a3ee5efbf1cfc9f81ab82d1285f0fe38b1ccb2daf6c")

addappid(1882510)
addappid(3864310)