-- generated by KeySteam
-- update time: 2025-10-08
-- app_name: Leisure Suit Larry - Wet Dreams Don't Dry

addappid(765870)

addappid(765871,0,"93e21949ba95d930ab5863f6014c8dd93a534b75a8144aacf43304d091991628")

addappid(1460880)