-- generated by KeySteam
-- update time: 2019-01-28
-- app_name: Fairy of the treasures

addappid(770400)

addappid(770401,0,"78980056981f05a60956d6716402f8d6941b3762dc4b8bb564eef13db67bf84c")

addappid(792360)
addappid(816050)
addappid(973490)
addappid(997740)