-- generated by KeySteam
-- update time: 2019-03-30
-- app_name: 永遠消失的幻想鄉 ～ The Disappearing of Gensokyo

addappid(776490)

addappid(776491,0,"69fca9154f831bbcd5c53ce8e95a2a7b986a2a9a2858071b3ba4061ae7dd7a7d")

addappid(778530)
addappid(779280)
addappid(780980)
addappid(780990)
addappid(781010)
addappid(781020)