-- generated by KeySteam
-- update time: 2018-01-18
-- app_name: Clicker: Mining Simulator

addappid(776890)

addappid(776891,0,"c4533292a5befa9f0da637d536e2d58b0dab34a54e1a0b9bf85c61d4aad0f183")

addappid(818190)