-- generated by KeySteam
-- update time: 2021-09-21
-- app_name: Vagante

addappid(323220,0,"eca57085b3803ff1fa1fc6fd6a07ef7a7cecc212f0f7d60c544775498551e2cb")

addappid(323221,0,"c303363ce4304b4fd265e8328cdacbebed351f897d5c3bbb151047fc645e7429")
