-- generated by KeySteam
-- update time: 2023-03-16
-- app_name: Surviving the Aftermath

addappid(684450,0,"04f18aabc8d04163851464b7137ad946facb2c2dfecdf3e4ba0b7cb9afb1b820")

addappid(684451,0,"ecae554f887c65bddfa54bffde64e0fe5c4315fb7bd3421186694d4b3555b45a")

addappid(1436890)
addappid(1600410)
addappid(1766280)
addappid(1803780)
addappid(1803781)
addappid(1803782)
addappid(2146190)