-- generated by KeySteam
-- update time: 2026-02-18
-- app_name: Heads Will Roll: Reforged

addappid(687800,0,"6fe52b54410a0c96b3c7a40befe006755fbed088972f30fde2c25ecfbc0abad8")

addappid(687801,0,"c2ca504542832cb9bfbb6785fafb8bd15bf790b11ca42c4c627bebcdbdf13e9c")

addappid(2517510)
addappid(2618340)
addappid(2747080)
addappid(2850080)
addappid(3172940)
addappid(3857000)
addappid(4177410)