-- generated by KeySteam
-- update time: 2025-11-04
-- app_name: Ash of Gods: Redemption

addappid(691690)

addappid(691691,0,"adf23d350fe3a0088c7cc82a54b5ca9bb6aa3f9b8f8ee8abab0e0f27854a306c")

addappid(820860)
addappid(820870)