-- generated by KeySteam
-- update time: 2025-10-03
-- app_name: For the Queen

addappid(2261050)

addappid(2261051,0,"a1535ad514a50c3d97428c97bccc22c05317da6c05238b2ed88bb045a236789b")

addappid(2478570)
addappid(2773510)