-- generated by KeySteam
-- update time: 2023-03-09
-- app_name: Senpai Puzzle: Waifu Summer

addappid(2266850)

addappid(2266851,0,"e97e7583e78db0b9d50d7e8f875af7656c03697d3b426f3fe6441cede193da6a")

addappid(2266880)
addappid(2314370)
addappid(2314371)
addappid(2314372)
addappid(2315740)
addappid(2315741)
addappid(2315743)
addappid(2315744)
addappid(2315745)
addappid(2315746)
addappid(2315747)
addappid(2315748)
addappid(2315760)
addappid(2315761)
addappid(2315762)
addappid(2315763)
addappid(2315764)
addappid(2315765)
addappid(2315766)
addappid(2315767)