-- generated by KeySteam
-- update time: 2025-09-30
-- app_name: finland corruption simulator

addappid(2266190)

addappid(2266191,0,"46ba7f5076739c2a02e8edce039fd9749ebcebd5ae63f5e8ed52aafd970dadec")

addappid(2643800)
addappid(2896060)