-- generated by KeySteam
-- update time: 2024-01-28
-- app_name: 风与鸟 - Wind and Bird

addappid(2269860)

addappid(2269861,0,"e847ca38c36b364acaebae69c5c15143c55a0e46db5bc5889e925f6c6e77660f")

addappid(2774590)
addappid(2774600)