-- generated by KeySteam
-- update time: 2026-03-25
-- app_name: NSFW Solitaire

addappid(2274120)

addappid(2274121,0,"8ab778e04e57fdbbab09a082231e133ae4f45bf4a89761efec9472468bec95c8")

addappid(3092690)
addappid(3831360)
addappid(3880230)
addappid(4015910)
addappid(4160570)
addappid(4185840)
addappid(4193710)
addappid(4208020)
addappid(4231120)
addappid(4255020)
addappid(4265010)
addappid(4280200)
addappid(4297330)
addappid(4303230)
addappid(4317890)
addappid(4351630)
addappid(4402440)
addappid(4424960)
addappid(4456870)