-- generated by KeySteam
-- update time: 2025-04-17
-- app_name: Kemono Heroes

addappid(2787700)

addappid(2787701,0,"a5c0c6ce33ba8b9c8865f8e915cae3fd143e9e99f0d76f80947c5ba8131c4f4f")

addappid(3541220)