-- generated by KeySteam
-- update time: 2025-06-25
-- app_name: Summer For You

addappid(2066980)

addappid(2066981,0,"6b86aaa3c0186b88938b716851a58479cf34d43be6b5c769da79de2d446d686a")

addappid(3213510)
addappid(3213520)
addappid(3213530)