-- generated by KeySteam
-- update time: 2026-02-17
-- app_name: Ravenswatch 鸦卫奇旅

addappid(2071280)

addappid(2071281,0,"708c675853989cbd400455e166d30f9dec051473847f4577ef48f7c9331edb97")

addappid(3113100)
addappid(3113110)
addappid(3113120)
addappid(3113130)
addappid(3393430)
addappid(3607920)
addappid(3607930)
addappid(3607940)
addappid(3607950)