-- generated by KeySteam
-- update time: 
-- app_name: 隐秘的角落

addappid(2071200)

addtoken(2071200,"18132222744142005927")

addappid(2071201,0,"1a87b391b41bebc4448fdf102ac6cbf86eb39a518c275bc3f74f5a9050f577a8")
