-- generated by KeySteam
-- update time: 2026-03-17
-- app_name: DRAGON BALL GEKISHIN SQUADRA

addappid(2072560)

addappid(2072561,0,"08d9bec08f2cd9753d164478dadaf58e95a81b7d4e48197fd3dca8f2397f43f7")
