-- generated by KeySteam
-- update time: 2026-03-06
-- app_name: 魔饮心语

addappid(2076140)

addappid(2076141,0,"38c00b2e11a56563435dc1469d94558e9c10aa7b35096d267019be9fd87ec844")
addappid(3047210,0,"01842d4b8f01a186b76208cf8cfd86487e8568f7c5c09e032301d5c18fa80040")

addappid(3054560)
addappid(3054600)
addappid(3054620)
addappid(3244740)
addappid(3268390)
addappid(4028280)