-- generated by KeySteam
-- update time: 2019-07-24
-- app_name: Truth: Disorder II

addappid(847580)

addappid(847583,0,"e78b70389bdc1f4b58a2f67cf824984429d8089aba7d76aa868447d7911dfe4f")
addappid(847584,0,"81ea0eacf34b72f40c1d331121a44cf6c717f8457da28d25893ae7d09ddfa09a")

addappid(923930)
addappid(973520)
addappid(996900)