-- generated by KeySteam
-- update time: 
-- app_name: Pizza Connection 3 - Pizza Creator

addappid(851330)

addtoken(851330,"3985689727236140013")

addappid(851331,0,"91392c1f5fecfb527cb7b4be7154f779d742fce5db6186f49655180e753867d7")
