-- generated by KeySteam
-- update time: 2022-06-16
-- app_name: Ultimate Sudoku Collection

addappid(851810)

addappid(851812,0,"bdfd9edd9422ffa7b64386dc53f5b3912d311d42190adf9dd1e838dad450001d")
addappid(853370,0,"8f06d1ae496cf488157f05cce541dba932cd02328cced2132720d05e01865ae4")
