-- generated by KeySteam
-- update time: 2025-09-01
-- app_name: Spiral Clicker

addappid(950860,0,"7ca19b1be3edc0260b17af62d00bd8417f2626077320f7e576b201bfd757e0f8")

addappid(950861,0,"a5b58056e4edfa4aeddea784bea57c797d2b881c01720ab040fb90b6a792a5a6")

addappid(1045810)