-- generated by KeySteam
-- update time: 2018-10-29
-- app_name: OVERKILL's The Walking Dead - BETA

addappid(952440)

addappid(952441,0,"5c6112da7cecb5d5fa8f484c4a139457a2a4b89010b9e6033fa55049310c6aa9")
