-- generated by KeySteam
-- update time: 2021-12-16
-- app_name: Terminator: Resistance

addappid(954740)

addappid(954741,0,"4159d3017619889a426e09a0c6691af103245053c33f26593c6e8e82c54a50d3")

addappid(1451140)
addappid(1755190)