-- generated by KeySteam
-- update time: 2026-02-25
-- app_name: Zoom Player Steam Edition

addappid(269550)

addappid(269551,0,"4c9f38bda241d658ae0875e53a95399ef1e3dd3713b9d20bbe917cb115db3b47")

addappid(2603900)