-- generated by KeySteam
-- update time: 2024-04-24
-- app_name: Asian Foxes

addappid(2833960)

addappid(2833961,0,"4f2bfbfc476005e67571dea768a0d2b861aa1c823698caaa08f06c7035f77c40")

addappid(2873730)