-- generated by KeySteam
-- update time: 2024-06-18
-- app_name: 纯爱声放送 Voice Love on Air

addappid(2321120)

addappid(2321121,0,"1d7072e2c9d2388fa7e05e5bab9ca43ec79cdc2d3270c3de29886d6fff26fc70")

addappid(2875420)
addappid(3052430)
addappid(3058340)