-- generated by KeySteam
-- update time: 
-- app_name: CD 2：陷阱大师

addappid(2330870,0,"3091119ef09a2ab3ae111241380ab4d87280a2e1439347d3114285d2f74cbfd3")

addtoken(2330870,"12104251757833054516")

addappid(2330871,0,"de92f1d5e030e05bc7534ad3e45745a9bd0c0fbfb525ff03a153d74c5b720abf")
