-- generated by KeySteam
-- update time: 2025-10-06
-- app_name: Vasilisa and Baba Yaga

addappid(2331070)

addappid(2331071,0,"195b6d43a192fece38c10a7f3deee99db7016a82ac177254bc8d11169422387a")

addappid(3666700)