-- generated by KeySteam
-- update time: 2021-03-19
-- app_name: JumpBall 2

addappid(750870)

addappid(750871,0,"6e70c2d42657bec97729c570e7c9d5c0cd68621445a82d8133e00fcad6930851")

addappid(1575340)
addappid(1575341)