-- generated by KeySteam
-- update time: 2019-07-02
-- app_name: Earthfall

addappid(415590)

addappid(415591,0,"aea7b15d78d3bf150bc12d1c108701613ef7280234d444654423ddc03b0dbe35")

addappid(578340)
addappid(874800)