-- generated by KeySteam
-- update time: 2026-02-26
-- app_name: 时光超市 Playtest

addappid(4071010,0,"d975743241be0bb082d7ee37bfce99efa7e767959303b4a2464a02cbbc5b7a5d")

addappid(4071011,0,"3b621286e990cdae631bdf2fcb08481ac3777e74be309789ae6f0e5578b39227")
