-- generated by KeySteam
-- update time: 2018-05-06
-- app_name: Bitcoin Trader

addappid(837900)

addappid(837901,0,"6f5289ef6ddb52bc94096aa21ba040acf269efbfe051044b76e788e753a4695e")

addappid(856630)