-- generated by KeySteam
-- update time: 2026-03-19
-- app_name: 太吾绘卷 The Scroll Of Taiwu

addappid(838350,0,"bf086ed374abbdc30220a8965af14256dd7f48cb48cfe8f47d4f1eaedc79fd2e")

addappid(838351,0,"7de3577779d63fd52db715a1898f8353eb0f5f4096ab3391f77b582621e1adb8")
addappid(946970,0,"6eb479723fd905892e55add18fe531a67b7e3c42595302faa5685e47fd7603c3")

addappid(2172690)
addappid(2241120)
addappid(2764950)
addappid(2764960)
addappid(3464590)