-- generated by KeySteam
-- update time: 2024-06-06
-- app_name: 小石冒险 Koishi Adventure⁓

addappid(2906930)

addappid(2906931,0,"9f1221beec8dffe82cbf83a8e017f9032bc89e2e3f52c67c93d12ff3fcb8c222")

addappid(3009580)
addappid(3032880)