-- generated by KeySteam
-- update time: 2026-02-23
-- app_name: 薇拉里娅的烛花 （薇拉里娅1）

addappid(2859860)

addappid(2859863,0,"dbdf11de9e490280e6d377345bc39a5f5bfcd69237235e3123708f4d3bebf2f5")

addappid(3706240)
addappid(3706300)
addappid(3720480)
addappid(3835470)