-- generated by KeySteam
-- update time: 2021-02-28
-- app_name: VR Hentai Date

addappid(1526230)

addappid(1526231,0,"8780d5a4f3732005999ffdfa14d78325f34b23f40530aac8c74cfff0ed954ab3")

addappid(1534100)
addappid(1535540)
addappid(1539200)