-- generated by KeySteam
-- update time: 2025-08-28
-- app_name: Otherwar

addappid(1526870)

addappid(1526871,0,"1645d3ee1125c44d41bf2adba218e5d6b066653d58501dda24f44b802ee0b607")

addappid(1526880)
addappid(1576040)
addappid(1576041)