-- generated by KeySteam
-- update time: 
-- app_name: Castle Crashers

addappid(204360,0,"f5bb85b444dee434a3aa48e4e0ff658c8ec1a74ce850aa9c986f5cefec9386cf")

addtoken(204360,"14285758721387452983")

addappid(204361,0,"2428bf7adcf5bac5af5d4f346adeea328831349da1ac601a9d6c33db6d6b5677")
