-- generated by KeySteam
-- update time: 2019-07-27
-- app_name: 上帝之城 I：监狱帝国 [City of God I - Prison Empire]

addappid(466860,0,"2fb28824d5a45c951dfb5c83eba8f06cf29dfe767c401965faac943ad13a0da1")

addappid(466861,0,"4f514e74b0df3452ee09cfb0e8189dcff9e77a5eebb7bafc693e37837b5e93a6")

addappid(851318)
addappid(949610)
addappid(1121390)